In [1]:
import os
import sys

# Standard interactive replacement for the 'parent directory' hack
parent_dir = os.path.abspath(os.path.join(os.getcwd(), '..'))
sys.path.append(parent_dir)

import pandas as pd
import numpy as np
from tqdm.notebook import tqdm

from PPRCalculator import PPRCalculator
from ModelData import ModelData

In [61]:
def apply_ecopath_defaults(df, DC, det_fate=None, zero_catch=False, zero_biomass_accum=False, default_gs=False):
    """
    Applies Ecopath defaults and ensures flows are synced with ratios.
    Assumes p, q, ee, and catch are given. assumes p, q not given for detritus group.
        calculates M0 = p*(1-ee)
    Assumes gs is 0.2 for regular groups and 0 for pp, det, diet_import.
        calculates egestion = q*gs.
    Assumes biomas_accum, net_migration are 0 where currently nan.
    Calculates once cell missing from p, q, egestion, respiration.
    Calculates predation = Z.sum(axis=1).
        Calculates once cell missing from M0, predation, catch, biomass_accum, net_migration.
    """
    df = df.sort_index(ascending=False)
    is_regular = df["trophic_info"] == "Regular"
    is_import = df["trophic_info"] == "Import"
    is_det = df["trophic_info"] == "DET"
    is_pp = df["trophic_info"] == "PP"

    # original_nas = df.isna()

    # cols with constant value of 0 or 1:
    cols_where_default_is_zero = ['detritus_import', 'immigration', 'emigration', 'net_migration']
    if zero_catch:
        cols_where_default_is_zero.append('catch')
    if zero_biomass_accum:
        cols_where_default_is_zero.append('biomass_accum')
    fill_dict = {col: 0 for col in cols_where_default_is_zero}
    df = df.fillna(fill_dict)
    df.loc[:, 'biomass'] = df['biomass'].fillna(1)

    # get Z which is correct for all regular groups:
    Z = DC.mul(df['q'].fillna(0), axis='index')
    Z.loc[is_det | is_pp | is_import, :] = 0
    Z = Z.sort_index(ascending=False).sort_index(ascending=False, axis=1)

    # set default values for non-regular groups:
    df.loc[is_pp | is_import | is_det, ['egestion', 'respiration']] = 0
    df.loc[is_import | is_det, 'M0'] = 0
    df.loc[is_import | is_det, 'ee'] = 1

    # fillna for gs and egestion:
    df.loc[~is_regular, 'gs'] = df.loc[~is_regular, 'gs'].fillna(0)
    if default_gs:
        df.loc[is_regular, 'gs'] = df.loc[is_regular, 'gs'].fillna(0.2)

    # Sync gs -> egestion
    mask_sync = df['egestion'].isna() & df['q'].notna() & df['gs'].notna()
    df.loc[mask_sync, 'egestion'] = df['q'] * df['gs']

    # Sync ee -> M0
    mask_sync = df['M0'].isna() & df["p"].notna() & df["ee"].notna()
    df.loc[mask_sync, 'M0'] = df["p"] * (1 - df["ee"])

    # q for detritus:
    df['flow_to_det'] = df['M0'] + df['egestion']
    if det_fate is not None:
        detritus_inflows = det_fate.mul(df['flow_to_det'], axis='index').sum(axis=0)
        df.loc[is_det, 'q'] = df.loc[is_det, 'q'].fillna(detritus_inflows)
    else:
        df.loc[is_det, 'q'] = df.loc[is_det, 'q'].fillna(df['M0'].sum() + df['egestion'].sum())  # set q of detritus as M0.sum() + egestion.sum()

    # predation:
    df.loc[:, 'predation'] = Z.sum(axis=0)

    # for non-regular groups, egestion and respiration are nan so q = p:
    df.loc[is_det, 'p'] = df['q']
    df.loc[is_pp | is_import, 'q'] = df['p']
    
    # pb and qb:
    df.loc[:, 'pb'] = (df['p'] / df['biomass']).fillna(0)
    df.loc[:, 'qb'] = (df['q'] / df['biomass']).fillna(0)

    def _solve_linear_equation(df, eq_cols, signs):
        # Identify rows where exactly ONE variable is missing (otherwise it's unsolvable this way)
        solvable_mask = df[eq_cols].isna().sum(axis=1) == 1

        # Calculate the net sum of all known terms (Pandas ignores NaNs by default in .sum)
        balance_sum = (df[eq_cols] * signs).sum(axis=1, skipna=True)

        # Fill the missing cells
        for col in eq_cols:
            # Target rows where THIS column is the missing one, and the equation is solvable
            target_cells = df[col].isna() & solvable_mask
            
            # The missing value is the negative balance_sum divided by the column's sign
            df.loc[target_cells, col] = -balance_sum[target_cells] / signs[col]
        
        return df
    
    # consumption equation:
    eq_cols = ['q', 'p', 'respiration', 'egestion']
    signs = pd.Series({
        'q': 1, 
        'p': -1, 
        'respiration': -1, 
        'egestion': -1, 
    })
    df = _solve_linear_equation(df, eq_cols, signs)
    
    # production equation:
    eq_cols = ['p', 'M0', 'catch', 'predation', 'net_migration', 'biomass_accum']
    signs = pd.Series({
        'p': 1, 
        'M0': -1, 
        'catch': -1, 
        'predation': -1, 
        'net_migration': -1, 
        'biomass_accum': -1
    })
    df = _solve_linear_equation(df, eq_cols, signs)

    # finalize ratios:
    df.loc[is_regular, 'ee'] = 1 - (df['M0'] / df['p'])
    df.loc[is_regular, 'gs'] = (df['egestion'] / df['q'])
    df['ge'] = (df['p'] / df['q']).fillna(0)
    df['flow_to_det'] = df['flow_to_det'].fillna(df['M0'] + df['egestion'])

    return df

In [62]:
model = PPRCalculator(116)
model.get_groups_df().round(5)[['group_name', 'trophic_info', 'tl', 'ee', 'p', 'q', 'biomass_accum', 'net_migration', 'M0', 'predation', 'catch', 'gs', 'egestion', 'respiration']]
model.get_groups_df().round(5)

,group_name,trophic_info,tl,ge,ee,catch,biomass,pb,qb,p,...,M0,gs,egestion,respiration,biomass_accum,emigration,immigration,net_migration,flow_to_det,detritus_import
group_seq,,,,,,,,,,,,,,,,,,,,,
33,diet_import,Import,1.00000,1.00000,1.00000,0.00000,NaN,NaN,NaN,0.00000,...,0.00000,0.000,0.00000,0.00000,0.00000,0.0,0.0,0.0,NaN,NaN
32,Detritus,DET,1.00000,1.00000,0.99965,0.00000,132.61000,NaN,NaN,1283.66658,...,0.00000,0.000,0.00000,0.00000,512.76917,0.0,0.0,0.0,NaN,0.0
31,Phytoplankton,PP,1.00000,1.00000,0.85716,0.00000,12.95000,105.03494,0.00000,1360.20250,...,194.28466,0.000,0.00000,0.00000,0.00000,0.0,0.0,0.0,194.28466,0.0
30,Small zooplankton,Regular,2.10254,0.25000,0.79477,0.00000,71.86000,4.81501,19.26006,346.00691,...,71.01249,0.455,629.73255,408.28815,0.00000,0.0,0.0,0.0,700.74504,0.0
29,Large zooplankton,Regular,2.41896,0.13174,0.54362,0.00000,14.68000,2.62915,19.95700,38.59588,...,17.61443,0.500,146.48436,107.88848,0.00000,0.0,0.0,0.0,164.09879,0.0
28,Other ben. inver.,Regular,2.00000,0.30000,0.32719,0.00000,5.70000,1.60936,5.36454,9.17336,...,6.17197,0.300,9.17336,12.23115,0.00000,0.0,0.0,0.0,15.34533,0.0
27,Polychaetes,Regular,2.15473,0.27396,0.54807,0.00000,14.82000,2.11052,7.70368,31.27794,...,14.13548,0.100,11.41685,71.47374,0.00000,0.0,0.0,0.0,25.55233,0.0
26,Molluscs,Regular,2.00000,0.09000,0.02180,0.03450,53.44000,0.42948,4.77202,22.95153,...,22.45119,0.300,76.50509,155.56035,0.00000,0.0,0.0,0.0,98.95628,0.0
25,Echinoderms,Regular,2.00000,0.30000,0.02321,0.00000,81.90000,0.41024,1.36747,33.59866,...,32.81892,0.300,33.59866,44.79822,0.00000,0.0,0.0,0.0,66.41758,0.0
24,Large crustacea,Regular,3.07794,0.21992,0.40124,0.04220,1.59000,0.29834,1.35659,0.47437,...,0.28403,0.100,0.21570,1.46691,0.00000,0.0,0.0,0.0,0.49973,0.0
23,Shrimp,Regular,2.26590,0.30000,0.95150,0.08310,0.68000,1.93333,6.44449,1.31466,...,0.06376,0.100,0.43823,2.62937,0.00000,0.0,0.0,0.0,0.50198,0.0
22,Plank. small pelagics,Regular,3.09228,0.29407,0.94643,0.21100,1.55000,0.47900,1.62886,0.74245,...,0.03977,0.300,0.75742,1.02486,0.00000,0.0,0.0,0.0,0.79719,0.0
21,Pisci. small pelagics,Regular,3.13091,0.27478,0.69150,0.02350,2.12000,0.31901,1.16094,0.67630,...,0.20863,0.300,0.73836,1.04654,0.00000,0.0,0.0,0.0,0.94699,0.0
20,Large pelagics,Regular,3.86473,0.17390,0.71207,0.00150,0.04000,0.25075,1.44193,0.01003,...,0.00289,0.100,0.00577,0.04188,0.00000,0.0,0.0,0.0,0.00866,0.0
19,Arctic cod,Regular,3.34931,0.30001,0.89888,0.00000,0.02000,0.53134,1.77107,0.01063,...,0.00107,0.100,0.00354,0.02125,0.00000,0.0,0.0,0.0,0.00462,0.0
18,Sand lance,Regular,3.12862,0.13492,0.94694,0.00000,1.14000,1.08915,8.07231,1.24164,...,0.06588,0.234,2.15337,5.80743,0.00000,0.0,0.0,0.0,2.21925,0.0
17,Capelin,Regular,3.23458,0.30001,0.94913,0.02720,9.52000,0.95945,3.19803,9.13395,...,0.46466,0.100,3.04453,18.26679,0.00000,0.0,0.0,0.0,3.50919,0.0
16,Small demersals,Regular,3.09813,0.30000,0.94312,0.00000,0.97000,0.46524,1.55082,0.45128,...,0.02567,0.300,0.45129,0.60173,0.00000,0.0,0.0,0.0,0.47696,0.0
15,Large demersals,Regular,3.79172,0.15432,0.73320,0.01020,0.94000,0.16005,1.03713,0.15045,...,0.04014,0.300,0.29247,0.53199,0.00000,0.0,0.0,0.0,0.33261,0.0
14,Redfish,Regular,3.58579,0.14009,0.94967,0.29000,7.16000,0.23670,1.68964,1.69476,...,0.08529,0.300,3.62935,6.77373,0.00000,0.0,0.0,0.0,3.71465,0.0
13,Skates,Regular,3.92715,0.10000,0.96177,0.00000,0.23000,0.20327,2.03269,0.04675,...,0.00179,0.300,0.14026,0.28051,0.00000,0.0,0.0,0.0,0.14204,0.0
12,Flounders,Regular,3.11617,0.30000,0.94239,0.00810,0.84000,0.30147,1.00490,0.25324,...,0.01459,0.300,0.25323,0.33764,0.00000,0.0,0.0,0.0,0.26782,0.0
11,American plaice,Regular,3.50272,0.30000,0.69217,0.01830,1.06000,0.38455,1.28183,0.40762,...,0.12548,0.300,0.40762,0.54350,0.00000,0.0,0.0,0.0,0.53310,0.0
10,Small Green. halibut,Regular,3.99863,0.10000,0.68747,0.00000,0.48000,0.23028,2.30275,0.11054,...,0.03455,0.100,0.11053,0.88425,0.00000,0.0,0.0,0.0,0.14508,0.0
9,Large Green. halibut,Regular,4.00789,0.10000,0.95191,0.03950,0.31000,0.15994,1.59935,0.04958,...,0.00238,0.300,0.14874,0.29748,0.00000,0.0,0.0,0.0,0.15112,0.0
8,Small cod,Regular,3.59518,0.20334,0.80939,0.00090,0.82000,0.81991,4.03212,0.67233,...,0.12815,0.300,0.99190,1.64211,0.00000,0.0,0.0,0.0,1.12005,0.0
7,Large cod,Regular,4.22902,0.29961,0.44925,0.69400,2.00900,0.82620,2.75762,1.65984,...,0.91415,0.300,1.66202,2.21820,0.00000,0.0,0.0,0.0,2.57617,0.0
6,Seabirds,Regular,4.14175,0.00955,0.28727,0.00030,0.00260,0.40166,42.05056,0.00104,...,0.00074,0.300,0.03280,0.07549,0.00000,0.0,0.0,0.0,0.03354,0.0
5,Harbour seals,Regular,4.15862,0.01000,0.00000,0.00000,0.00200,0.07094,7.09108,0.00014,...,0.00014,0.300,0.00425,0.00979,0.00000,0.0,0.0,0.0,0.00440,0.0
4,Grey seals,Regular,4.51601,0.01000,0.49246,0.00070,0.01300,0.10934,10.93336,0.00142,...,0.00072,0.300,0.04264,0.09807,0.00000,0.0,0.0,0.0,0.04336,0.0
3,Hooded seals,Regular,4.85766,0.00553,0.05687,0.00001,0.00329,0.05341,9.65895,0.00018,...,0.00017,0.300,0.00954,0.02208,0.00000,0.0,0.0,0.0,0.00971,0.0
2,Harp seals,Regular,4.24734,0.01000,0.95000,0.00420,0.04296,0.10291,10.29124,0.00442,...,0.00022,0.300,0.13264,0.30506,0.00000,0.0,0.0,0.0,0.13286,0.0
1,Cetacea,Regular,4.09398,0.01000,0.04589,0.00040,0.12000,0.07264,7.26505,0.00872,...,0.00832,0.100,0.08718,0.77591,0.00000,0.0,0.0,0.0,0.09550,0.0

In [66]:
groups_df = model.get_groups_df().copy()
# groups_df[['egestion', 'respiration', 'biomass_accum', 'emigration', 'immigration', 'net_migration', 'M0']] = np.nan
groups_df[['M0', 'ee', 'respiration', 'egestion', 'biomass_accum', 'gs']] = np.nan

apply_ecopath_defaults(groups_df, model.get_DC(), det_fate=model._det_fate, zero_biomass_accum=False, default_gs=False).round(6)
# groups_df

,group_name,trophic_info,tl,ge,ee,catch,biomass,pb,qb,p,...,M0,gs,egestion,respiration,biomass_accum,emigration,immigration,net_migration,flow_to_det,detritus_import
group_seq,,,,,,,,,,,,,,,,,,,,,
33,diet_import,Import,1.000000,0.000000,1.0,0.00000,1.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
32,Detritus,DET,1.000000,1.000000,1.0,0.00000,132.610000,9.680013,9.680013,1283.666580,...,0.0,0.0,0.0,0.0,512.769167,0.0,0.0,0.0,0.0,0.0
31,Phytoplankton,PP,1.000000,1.000000,NaN,0.00000,12.950000,105.034942,105.034942,1360.202500,...,NaN,0.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0
30,Small zooplankton,Regular,2.102536,0.250000,NaN,0.00000,71.860000,4.815014,19.260056,346.006906,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
29,Large zooplankton,Regular,2.418964,0.131741,NaN,0.00000,14.680000,2.629147,19.956997,38.595878,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
28,Other ben. inver.,Regular,2.000000,0.300000,NaN,0.00000,5.700000,1.609362,5.364541,9.173364,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
27,Polychaetes,Regular,2.154734,0.273963,NaN,0.00000,14.820000,2.110523,7.703680,31.277944,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
26,Molluscs,Regular,2.000000,0.090000,NaN,0.03450,53.440000,0.429482,4.772024,22.951529,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
25,Echinoderms,Regular,2.000000,0.300000,NaN,0.00000,81.900000,0.410240,1.367467,33.598660,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
24,Large crustacea,Regular,3.077945,0.219922,NaN,0.04220,1.590000,0.298344,1.356590,0.474366,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
23,Shrimp,Regular,2.265897,0.299997,NaN,0.08310,0.680000,1.933326,6.444493,1.314662,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
22,Plank. small pelagics,Regular,3.092282,0.294071,NaN,0.21100,1.550000,0.479000,1.628857,0.742450,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
21,Pisci. small pelagics,Regular,3.130912,0.274783,NaN,0.02350,2.120000,0.319007,1.160942,0.676295,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
20,Large pelagics,Regular,3.864730,0.173897,NaN,0.00150,0.040000,0.250748,1.441931,0.010030,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
19,Arctic cod,Regular,3.349314,0.300012,NaN,0.00000,0.020000,0.531340,1.771066,0.010627,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
18,Sand lance,Regular,3.128618,0.134925,NaN,0.00000,1.140000,1.089154,8.072308,1.241635,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
17,Capelin,Regular,3.234585,0.300012,NaN,0.02720,9.520000,0.959449,3.198032,9.133951,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
16,Small demersals,Regular,3.098132,0.299996,NaN,0.00000,0.970000,0.465242,1.550825,0.451285,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
15,Large demersals,Regular,3.791716,0.154321,NaN,0.01020,0.940000,0.160052,1.037133,0.150449,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
14,Redfish,Regular,3.585792,0.140088,NaN,0.29000,7.160000,0.236698,1.689643,1.694757,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
13,Skates,Regular,3.927148,0.100001,NaN,0.00000,0.230000,0.203271,2.032689,0.046752,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
12,Flounders,Regular,3.116166,0.300003,NaN,0.00810,0.840000,0.301472,1.004897,0.253236,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
11,American plaice,Regular,3.502715,0.300000,NaN,0.01830,1.060000,0.384549,1.281830,0.407622,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
10,Small Green. halibut,Regular,3.998634,0.100004,NaN,0.00000,0.480000,0.230284,2.302753,0.110536,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
9,Large Green. halibut,Regular,4.007891,0.100002,NaN,0.03950,0.310000,0.159938,1.599346,0.049581,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
8,Small cod,Regular,3.595177,0.203345,NaN,0.00090,0.820000,0.819911,4.032117,0.672327,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
7,Large cod,Regular,4.229020,0.299607,NaN,0.69400,2.009000,0.826202,2.757616,1.659840,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
6,Seabirds,Regular,4.141750,0.009552,NaN,0.00030,0.002600,0.401664,42.050556,0.001044,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
5,Harbour seals,Regular,4.158625,0.010004,NaN,0.00000,0.002000,0.070937,7.091081,0.000142,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
4,Grey seals,Regular,4.516014,0.010001,NaN,0.00070,0.013000,0.109341,10.933355,0.001421,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
3,Hooded seals,Regular,4.857662,0.005530,NaN,0.00001,0.003292,0.053410,9.658946,0.000176,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
2,Harp seals,Regular,4.247342,0.010000,NaN,0.00420,0.042961,0.102909,10.291240,0.004421,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
1,Cetacea,Regular,4.093985,0.009999,NaN,0.00040,0.120000,0.072643,7.265048,0.008717,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0