In [67]:
import os
import sys

# Standard interactive replacement for the 'parent directory' hack
parent_dir = os.path.abspath(os.path.join(os.getcwd(), '..'))
sys.path.append(parent_dir)

import pandas as pd
import numpy as np
from tqdm.notebook import tqdm

from PPRCalculator import PPRCalculator
from ModelData import ModelData

In [103]:
def apply_ecopath_defaults(df, DC, det_fate=None, zero_catch=False, zero_biomass_accum=False, default_gs=False):
    """
    Applies Ecopath defaults and ensures flows are synced with ratios.
    Assumes p, q, ee, and catch are given. assumes p, q not given for detritus group.
        calculates M0 = p*(1-ee)
    Assumes gs is 0.2 for regular groups and 0 for pp, det, diet_import.
        calculates egestion = q*gs.
    Assumes biomas_accum, net_migration are 0 where currently nan.
    Calculates once cell missing from p, q, egestion, respiration.
    Calculates predation = Z.sum(axis=1).
        Calculates once cell missing from M0, predation, catch, biomass_accum, net_migration.
    """
    df = df.sort_index(ascending=False)
    is_regular = df["trophic_info"] == "Regular"
    is_import = df["trophic_info"] == "Import"
    is_det = df["trophic_info"] == "DET"
    is_pp = df["trophic_info"] == "PP"

    # original_nas = df.isna()

    # cols with constant value of 0 or 1:
    cols_where_default_is_zero = ['detritus_import', 'immigration', 'emigration', 'net_migration']
    if zero_catch:
        cols_where_default_is_zero.append('catch')
    if zero_biomass_accum:
        cols_where_default_is_zero.append('biomass_accum')
    fill_dict = {col: 0 for col in cols_where_default_is_zero}
    df = df.fillna(fill_dict)
    df.loc[:, 'biomass'] = df['biomass'].fillna(1)
    # set biomass_accum for det to nan anyway:
    df.loc[is_det, 'biomass_accum'] = np.nan

    # get Z which is correct for all regular groups:
    Z = DC.mul(df['q'].fillna(0), axis='index')
    Z.loc[is_det | is_pp | is_import, :] = 0
    Z = Z.sort_index(ascending=False).sort_index(ascending=False, axis=1)

    # set default values for non-regular groups:
    df.loc[is_pp | is_import | is_det, ['egestion', 'respiration']] = 0
    df.loc[is_import | is_det, 'M0'] = 0
    df.loc[is_import | is_det, 'ee'] = 1

    # fillna for gs and egestion:
    df.loc[~is_regular, 'gs'] = df.loc[~is_regular, 'gs'].fillna(0)
    if default_gs:
        df.loc[is_regular, 'gs'] = df.loc[is_regular, 'gs'].fillna(0.2)

    # Sync gs -> egestion
    mask_sync = df['egestion'].isna() & df['q'].notna() & df['gs'].notna()
    df.loc[mask_sync, 'egestion'] = df['q'] * df['gs']

    # Sync ee -> M0
    mask_sync = df['M0'].isna() & df["p"].notna() & df["ee"].notna()
    df.loc[mask_sync, 'M0'] = df["p"] * (1 - df["ee"])

    # q for detritus:
    df['flow_to_det'] = df['M0'] + df['egestion']
    if det_fate is not None:
        detritus_inflows = det_fate.mul(df['flow_to_det'], axis='index').sum(axis=0)
        df.loc[is_det, 'q'] = df.loc[is_det, 'q'].fillna(detritus_inflows)
    else:
        df.loc[is_det, 'q'] = df.loc[is_det, 'q'].fillna(df['M0'].sum() + df['egestion'].sum())  # set q of detritus as M0.sum() + egestion.sum()

    # predation:
    df.loc[:, 'predation'] = Z.sum(axis=0)

    # for non-regular groups, egestion and respiration are nan so q = p:
    df.loc[is_det, 'p'] = df['q']
    df.loc[is_pp | is_import, 'q'] = df['p']
    
    # pb and qb:
    df.loc[:, 'pb'] = (df['p'] / df['biomass']).fillna(0)
    df.loc[:, 'qb'] = (df['q'] / df['biomass']).fillna(0)

    def _solve_linear_equation(df, eq_cols, signs):
        # Identify rows where exactly ONE variable is missing (otherwise it's unsolvable this way)
        solvable_mask = df[eq_cols].isna().sum(axis=1) == 1

        # Calculate the net sum of all known terms (Pandas ignores NaNs by default in .sum)
        balance_sum = (df[eq_cols] * signs).sum(axis=1, skipna=True)

        # Fill the missing cells
        for col in eq_cols:
            # Target rows where THIS column is the missing one, and the equation is solvable
            target_cells = df[col].isna() & solvable_mask
            
            # The missing value is the negative balance_sum divided by the column's sign
            df.loc[target_cells, col] = -balance_sum[target_cells] / signs[col]
        
        return df
    
    # consumption equation:
    eq_cols = ['q', 'p', 'respiration', 'egestion']
    signs = pd.Series({
        'q': 1, 
        'p': -1, 
        'respiration': -1, 
        'egestion': -1, 
    })
    df = _solve_linear_equation(df, eq_cols, signs)
    
    # production equation:
    eq_cols = ['p', 'M0', 'catch', 'predation', 'net_migration', 'biomass_accum']
    signs = pd.Series({
        'p': 1, 
        'M0': -1, 
        'catch': -1, 
        'predation': -1, 
        'net_migration': -1, 
        'biomass_accum': -1
    })
    df = _solve_linear_equation(df, eq_cols, signs)

    # finalize ratios:
    df.loc[is_regular, 'ee'] = 1 - (df['M0'] / df['p'])
    df.loc[is_regular, 'gs'] = (df['egestion'] / df['q'])
    df['ge'] = (df['p'] / df['q'])
    df['flow_to_det'] = df['flow_to_det'].fillna(df['M0'] + df['egestion'])

    return df

In [ ]:
import pandas as pd
import numpy as np
from scipy.optimize import minimize

def apply_lim(df, weight_flow=1.0, weight_guess=0.0):
    """
    Uses Linear Inverse Modeling (SLSQP) to fill in missing mass-balance 
    variables by dynamically registering active constraints and coordinating guesses.
    """
    df_out = df.copy()

    def _finalize_outputs(df_final):
        # EE
        df_final.loc[:, 'ee'] = np.where(
            df_final.loc[:, 'p'] != 0, 
            1 - (df_final.loc[:, 'M0'] / df_final.loc[:, 'p']), 
            0
        )
        # GS
        df_final.loc[:, 'gs'] = np.where(
            df_final.loc[:, 'q'] != 0, 
            df_final.loc[:, 'egestion'] / df_final.loc[:, 'q'], 
            0
        )
        # GE
        df_final['ge'] = np.where(df_final['q'] != 0, df_final['p'] / df_final['q'], 0)
        
        # Flow to Detritus
        df_final['flow_to_det'] = df_final['M0'] + df_final['egestion']
        
        return df_final

    cols_to_solve = ['q', 'p', 'respiration', 'egestion', 'M0', 'biomass_accum']
    records = df_out.to_dict('index')
    
    for idx, row in records.items():
        missing_cols = [c for c in cols_to_solve if pd.isna(row[c])]
        if not missing_cols:
            continue
            
        c_val = row['catch'] if pd.notna(row['catch']) else 0
        pr_val = row['predation'] if pd.notna(row['predation']) else 0
        nm_val = row['net_migration'] if pd.notna(row['net_migration']) else 0

        # --- 1. Coordinated Guess Variables ---
        q_guess = row['q'] if pd.notna(row['q']) else (row['p'] * 10 if pd.notna(row['p']) else 1.0)
        p_guess = row['p'] if pd.notna(row['p']) else (q_guess * 0.1)
        
        # Smart adaptation: If both P and Q are known, don't overshoot the available pool
        if pd.notna(row['q']) and pd.notna(row['p']):
            rem_pool = max(0.0, row['q'] - row['p'])
            resp_guess = row['respiration'] if pd.notna(row['respiration']) else (rem_pool * (0.7 / 0.9))
            egest_guess = row['egestion'] if pd.notna(row['egestion']) else (rem_pool * (0.2 / 0.9))
        else:
            resp_guess = row['respiration'] if pd.notna(row['respiration']) else (q_guess * 0.7)
            egest_guess = row['egestion'] if pd.notna(row['egestion']) else (q_guess * 0.2)
            
        m0_guess = row['M0'] if pd.notna(row['M0']) else (q_guess * 0.1)
        ba_guess = row['biomass_accum'] if pd.notna(row['biomass_accum']) else (p_guess - m0_guess - c_val - pr_val - nm_val)

        # Assemble variables and bounds
        x0 = []
        bounds = []
        for col in missing_cols:
            if col == 'q': x0.append(q_guess); bounds.append((0, None))
            elif col == 'p': x0.append(p_guess); bounds.append((0, None))
            elif col == 'respiration': x0.append(resp_guess); bounds.append((0, None))
            elif col == 'egestion': x0.append(egest_guess); bounds.append((0, None))
            elif col == 'M0': x0.append(m0_guess); bounds.append((0, None))
            elif col == 'biomass_accum': x0.append(ba_guess); bounds.append((None, None))

        x0_arr = np.array(x0)
        scale = np.where(np.abs(x0_arr) > 0.01, np.abs(x0_arr), 1.0)
        
        # --- 2. High-Speed Mapping Indices ---
        idx_q = missing_cols.index('q') if 'q' in missing_cols else -1
        idx_p = missing_cols.index('p') if 'p' in missing_cols else -1
        idx_r = missing_cols.index('respiration') if 'respiration' in missing_cols else -1
        idx_e = missing_cols.index('egestion') if 'egestion' in missing_cols else -1
        idx_m0 = missing_cols.index('M0') if 'M0' in missing_cols else -1
        idx_ba = missing_cols.index('biomass_accum') if 'biomass_accum' in missing_cols else -1

        # --- 3. Objective Function ---
        def objective(x):
            # Penalty A: Flow Penalty (Parsimony / Minimum Total Flow)
            # Minimizes the total magnitude of the actively solved flows
            flow_pen = np.sum(np.abs(x) / scale)
            
            # Penalty B: Guess Penalty (Biological Anchoring)
            # Minimizes squared deviation from your smart biological guesses (x0)
            guess_pen = np.sum(((x - x0_arr) / scale) ** 2)
            
            return (weight_flow * flow_pen) + (weight_guess * guess_pen)

        # --- 4. Dynamic Constraint Registration ---
        constraints = []
        
        # Consumption Balance (Only if Q, P, R, or U are being optimized)
        if any(c in missing_cols for c in ['q', 'p', 'respiration', 'egestion']):
            def eq_consumption(x):
                q_curr = x[idx_q] if idx_q >= 0 else q_guess
                p_curr = x[idx_p] if idx_p >= 0 else p_guess
                r_curr = x[idx_r] if idx_r >= 0 else resp_guess
                e_curr = x[idx_e] if idx_e >= 0 else egest_guess
                return q_curr - (p_curr + r_curr + e_curr)
            constraints.append({'type': 'eq', 'fun': eq_consumption})
            
        # Production Balance (Only if P, M0, or BA are being optimized)
        if any(c in missing_cols for c in ['p', 'M0', 'biomass_accum']):
            def eq_production(x):
                p_curr = x[idx_p] if idx_p >= 0 else p_guess
                m0_curr = x[idx_m0] if idx_m0 >= 0 else m0_guess
                ba_curr = x[idx_ba] if idx_ba >= 0 else ba_guess
                return p_curr - (m0_curr + c_val + pr_val + nm_val + ba_curr)
            constraints.append({'type': 'eq', 'fun': eq_production})

        # EE bounds (Only if P or M0 can actually change)
        if 'p' in missing_cols or 'M0' in missing_cols:
            # Upper Bound: EE <= 0.95 (Equivalent to: M0 - 0.05 * P >= 0)
            def ineq_ee_upper(x):
                p_curr = x[idx_p] if idx_p >= 0 else p_guess
                m0_curr = x[idx_m0] if idx_m0 >= 0 else m0_guess
                return m0_curr - (0.05 * p_curr)
            constraints.append({'type': 'ineq', 'fun': ineq_ee_upper})
            
            # Lower Bound: EE >= 0.0 (Equivalent to: P - M0 >= 0)
            def ineq_ee_lower(x):
                p_curr = x[idx_p] if idx_p >= 0 else p_guess
                m0_curr = x[idx_m0] if idx_m0 >= 0 else m0_guess
                return p_curr - m0_curr
            constraints.append({'type': 'ineq', 'fun': ineq_ee_lower})
            
        # GS Upper limit (Only if Q or Egestion can actually change)
        if 'q' in missing_cols or 'egestion' in missing_cols:
            # Enforce GS <= 0.35
            def ineq_gs_upper(x):
                q_curr = x[idx_q] if idx_q >= 0 else q_guess
                e_curr = x[idx_e] if idx_e >= 0 else egest_guess
                return 0.35 * q_curr - e_curr
            constraints.append({'type': 'ineq', 'fun': ineq_gs_upper})

            # Enforce GS >= 0.10
            def ineq_gs_lower(x):
                q_curr = x[idx_q] if idx_q >= 0 else q_guess
                e_curr = x[idx_e] if idx_e >= 0 else egest_guess
                return e_curr - (0.10 * q_curr)
            constraints.append({'type': 'ineq', 'fun': ineq_gs_lower})

        # --- 5. Run Optimizer ---
        res = minimize(
            objective, 
            x0_arr, 
            method='SLSQP', 
            bounds=bounds, 
            constraints=constraints,
            tol=1e-5,
            options={'maxiter': 1500, 'ftol': 1e-5}
        )

        if not res.success:
            print(f"LIM failed for group '{idx}': {res.message}")
        else:
            for i, col in enumerate(missing_cols):
                df_out.loc[idx, col] = res.x[i]

    return _finalize_outputs(df_out)

In [139]:
model = PPRCalculator(459)
model.get_groups_df().round(5)[['group_name', 'trophic_info', 'tl', 'ee', 'p', 'q', 'biomass_accum', 'net_migration', 'M0', 'predation', 'catch', 'gs', 'egestion', 'respiration']]
model.get_groups_df().round(5)

,group_name,trophic_info,tl,ge,ee,catch,biomass,pb,qb,p,...,M0,gs,egestion,respiration,biomass_accum,emigration,immigration,net_migration,flow_to_det,detritus_import
group_seq,,,,,,,,,,,,,,,,,,,,,
32,diet_import,Import,1.00000,1.00000,1.00000,0.00000,NaN,NaN,NaN,84.56694,...,0.00000,0.0,0.00000,0.00000,0.00000,0.0,0.0,0.0,NaN,NaN
31,Detritus,DET,1.00000,1.00000,0.00000,0.00000,15.07500,NaN,NaN,1642.61581,...,0.00000,0.0,0.00000,0.00000,491.83744,0.0,0.0,0.0,NaN,0.0
30,Phytoplankton,PP,1.00000,1.00000,0.84209,0.00000,32.00000,42.800,0.00,1369.59993,...,216.27271,0.0,0.00000,0.00000,0.00000,0.0,0.0,0.0,216.27271,0.0
29,Large zooplankton,Regular,3.00597,0.30000,0.15243,0.00000,9.63600,8.700,29.00,83.83320,...,71.05464,0.4,111.77760,83.83320,0.00000,0.0,0.0,0.0,182.83224,0.0
28,Small zooplankton,Regular,2.00301,0.29983,0.66559,0.00000,40.00000,17.300,57.70,692.00000,...,231.41099,0.4,923.20000,692.80000,0.00000,0.0,0.0,0.0,1154.61099,0.0
27,Large squids,Regular,4.39837,0.29004,0.35927,0.00001,0.17709,4.600,15.86,0.81460,...,0.52194,0.2,0.56172,1.43229,0.00000,0.0,0.0,0.0,1.08366,0.0
26,Small squids,Regular,3.86046,0.30005,0.95000,0.00000,1.15744,5.500,18.33,6.36594,...,0.31830,0.2,4.24319,10.60681,0.00000,0.0,0.0,0.0,4.56148,0.0
25,Other turtles,Regular,3.50449,0.04286,0.99000,0.00003,0.00077,0.150,3.50,0.00012,...,0.00000,0.2,0.00054,0.00203,0.00000,0.0,0.0,0.0,0.00054,0.0
24,Leatherback turtle,Regular,3.98591,0.04286,0.99000,0.00001,0.00057,0.150,3.50,0.00009,...,0.00000,0.2,0.00040,0.00151,0.00000,0.0,0.0,0.0,0.00040,0.0
23,Large mesopelagics,Regular,4.01639,0.10000,0.17684,0.00000,10.83300,0.355,3.55,3.84572,...,3.16563,0.2,7.69143,26.92000,0.00000,0.0,0.0,0.0,10.85706,0.0
22,Small mesopelagics,Regular,3.05416,0.25067,0.95000,0.00000,8.72407,3.760,15.00,32.80251,...,1.64013,0.2,26.17221,71.88634,0.00000,0.0,0.0,0.0,27.81234,0.0
21,Small coastal pelagics,Regular,2.95912,0.23907,0.95661,0.00580,0.24400,3.500,14.64,0.85400,...,0.03706,0.2,0.71443,2.00373,0.00000,0.0,0.0,0.0,0.75149,0.0
20,Small offshore pelagics,Regular,2.95843,0.24590,0.33238,0.00000,7.39400,3.600,14.64,26.61840,...,17.77089,0.2,21.64963,59.98013,0.00000,0.0,0.0,0.0,39.42052,0.0
19,Coastal predators,Regular,3.60409,0.09972,0.95000,0.01202,1.25736,0.720,7.22,0.90530,...,0.04527,0.2,1.81563,6.35722,0.00000,0.0,0.0,0.0,1.86090,0.0
18,Flyingfish,Regular,3.02923,0.16155,0.95000,0.00274,0.20825,4.000,24.76,0.83300,...,0.04165,0.2,1.03125,3.29201,0.00000,0.0,0.0,0.0,1.07290,0.0
17,Pelagic sharks,Regular,4.75657,0.04000,0.99000,0.00284,0.01160,0.400,10.00,0.00464,...,0.00005,0.2,0.02321,0.08820,0.00000,0.0,0.0,0.0,0.02326,0.0
16,Dolphinfish,Regular,4.43898,0.23600,0.95852,0.00361,0.02780,4.720,20.00,0.13122,...,0.00544,0.2,0.11120,0.31358,0.00000,0.0,0.0,0.0,0.11664,0.0
15,Wahoo,Regular,4.80637,0.07859,0.95000,0.00082,0.00104,2.500,31.81,0.00260,...,0.00013,0.2,0.00662,0.02387,0.00000,0.0,0.0,0.0,0.00675,0.0
14,Mackerels,Regular,4.26664,0.10572,0.64168,0.00748,0.06500,1.090,10.31,0.07085,...,0.02539,0.2,0.13403,0.46527,0.00000,0.0,0.0,0.0,0.15942,0.0
13,Other offshore predators,Regular,4.57175,0.25134,0.18473,0.00259,0.29000,1.870,7.44,0.54230,...,0.44212,0.2,0.43152,1.18378,0.00000,0.0,0.0,0.0,0.87364,0.0
12,Blackfin tuna,Regular,4.19564,0.18706,0.95000,0.00232,0.00520,1.850,9.89,0.00962,...,0.00048,0.2,0.01029,0.03152,0.00000,0.0,0.0,0.0,0.01077,0.0
11,Bigeye,Regular,4.50223,0.10000,0.76947,0.00057,0.00168,1.759,17.59,0.00295,...,0.00068,0.2,0.00589,0.02062,0.00000,0.0,0.0,0.0,0.00657,0.0
10,Albacore,Regular,4.58489,0.10000,0.88807,0.00291,0.00970,0.780,7.80,0.00757,...,0.00085,0.2,0.01514,0.05298,0.00000,0.0,0.0,0.0,0.01599,0.0
9,Skipjack,Regular,4.84840,0.09995,0.69496,0.00478,0.01194,1.960,19.61,0.02341,...,0.00714,0.2,0.04684,0.16397,0.00000,0.0,0.0,0.0,0.05399,0.0
8,Yellowfin,Regular,4.85886,0.12878,0.95000,0.00818,0.00586,2.000,15.53,0.01171,...,0.00059,0.2,0.01819,0.06106,0.00000,0.0,0.0,0.0,0.01878,0.0
7,Billfishes,Regular,4.36535,0.10000,0.95000,0.00121,0.00987,0.460,4.60,0.00454,...,0.00023,0.2,0.00908,0.03178,0.00000,0.0,0.0,0.0,0.00931,0.0
6,Swordfish,Regular,4.71001,0.06968,0.91142,0.00015,0.00700,0.370,5.31,0.00259,...,0.00023,0.2,0.00743,0.02715,0.00000,0.0,0.0,0.0,0.00766,0.0
5,Shallow-diving cetaceans,Regular,4.75667,0.00370,0.79593,0.00003,0.03362,0.050,13.50,0.00168,...,0.00034,0.2,0.09078,0.36143,0.00000,0.0,0.0,0.0,0.09112,0.0
4,Killer whales,Regular,4.75240,0.00207,0.32155,0.00001,0.00158,0.020,9.64,0.00003,...,0.00002,0.2,0.00305,0.01217,0.00000,0.0,0.0,0.0,0.00307,0.0
3,Deep-diving whales,Regular,5.12650,0.00735,0.00000,0.00000,0.01454,0.040,5.44,0.00058,...,0.00058,0.2,0.01582,0.06268,0.00000,0.0,0.0,0.0,0.01640,0.0
2,Baleen whales,Regular,4.30301,0.00328,0.00000,0.00000,0.02513,0.040,12.19,0.00101,...,0.00101,0.2,0.06126,0.24403,0.00000,0.0,0.0,0.0,0.06226,0.0
1,Seabirds,Regular,4.48557,0.00176,0.44659,0.00000,0.00020,0.130,73.69,0.00003,...,0.00001,0.2,0.00295,0.01176,0.00000,0.0,0.0,0.0,0.00296,0.0

In [147]:
groups_df = model.get_groups_df().copy()
groups_df.round(5)

,group_name,trophic_info,tl,ge,ee,catch,biomass,pb,qb,p,...,M0,gs,egestion,respiration,biomass_accum,emigration,immigration,net_migration,flow_to_det,detritus_import
group_seq,,,,,,,,,,,,,,,,,,,,,
32,diet_import,Import,1.00000,1.00000,1.00000,0.00000,NaN,NaN,NaN,84.56694,...,0.00000,0.0,0.00000,0.00000,0.00000,0.0,0.0,0.0,NaN,NaN
31,Detritus,DET,1.00000,1.00000,0.00000,0.00000,15.07500,NaN,NaN,1642.61581,...,0.00000,0.0,0.00000,0.00000,491.83744,0.0,0.0,0.0,NaN,0.0
30,Phytoplankton,PP,1.00000,1.00000,0.84209,0.00000,32.00000,42.800,0.00,1369.59993,...,216.27271,0.0,0.00000,0.00000,0.00000,0.0,0.0,0.0,216.27271,0.0
29,Large zooplankton,Regular,3.00597,0.30000,0.15243,0.00000,9.63600,8.700,29.00,83.83320,...,71.05464,0.4,111.77760,83.83320,0.00000,0.0,0.0,0.0,182.83224,0.0
28,Small zooplankton,Regular,2.00301,0.29983,0.66559,0.00000,40.00000,17.300,57.70,692.00000,...,231.41099,0.4,923.20000,692.80000,0.00000,0.0,0.0,0.0,1154.61099,0.0
27,Large squids,Regular,4.39837,0.29004,0.35927,0.00001,0.17709,4.600,15.86,0.81460,...,0.52194,0.2,0.56172,1.43229,0.00000,0.0,0.0,0.0,1.08366,0.0
26,Small squids,Regular,3.86046,0.30005,0.95000,0.00000,1.15744,5.500,18.33,6.36594,...,0.31830,0.2,4.24319,10.60681,0.00000,0.0,0.0,0.0,4.56148,0.0
25,Other turtles,Regular,3.50449,0.04286,0.99000,0.00003,0.00077,0.150,3.50,0.00012,...,0.00000,0.2,0.00054,0.00203,0.00000,0.0,0.0,0.0,0.00054,0.0
24,Leatherback turtle,Regular,3.98591,0.04286,0.99000,0.00001,0.00057,0.150,3.50,0.00009,...,0.00000,0.2,0.00040,0.00151,0.00000,0.0,0.0,0.0,0.00040,0.0
23,Large mesopelagics,Regular,4.01639,0.10000,0.17684,0.00000,10.83300,0.355,3.55,3.84572,...,3.16563,0.2,7.69143,26.92000,0.00000,0.0,0.0,0.0,10.85706,0.0
22,Small mesopelagics,Regular,3.05416,0.25067,0.95000,0.00000,8.72407,3.760,15.00,32.80251,...,1.64013,0.2,26.17221,71.88634,0.00000,0.0,0.0,0.0,27.81234,0.0
21,Small coastal pelagics,Regular,2.95912,0.23907,0.95661,0.00580,0.24400,3.500,14.64,0.85400,...,0.03706,0.2,0.71443,2.00373,0.00000,0.0,0.0,0.0,0.75149,0.0
20,Small offshore pelagics,Regular,2.95843,0.24590,0.33238,0.00000,7.39400,3.600,14.64,26.61840,...,17.77089,0.2,21.64963,59.98013,0.00000,0.0,0.0,0.0,39.42052,0.0
19,Coastal predators,Regular,3.60409,0.09972,0.95000,0.01202,1.25736,0.720,7.22,0.90530,...,0.04527,0.2,1.81563,6.35722,0.00000,0.0,0.0,0.0,1.86090,0.0
18,Flyingfish,Regular,3.02923,0.16155,0.95000,0.00274,0.20825,4.000,24.76,0.83300,...,0.04165,0.2,1.03125,3.29201,0.00000,0.0,0.0,0.0,1.07290,0.0
17,Pelagic sharks,Regular,4.75657,0.04000,0.99000,0.00284,0.01160,0.400,10.00,0.00464,...,0.00005,0.2,0.02321,0.08820,0.00000,0.0,0.0,0.0,0.02326,0.0
16,Dolphinfish,Regular,4.43898,0.23600,0.95852,0.00361,0.02780,4.720,20.00,0.13122,...,0.00544,0.2,0.11120,0.31358,0.00000,0.0,0.0,0.0,0.11664,0.0
15,Wahoo,Regular,4.80637,0.07859,0.95000,0.00082,0.00104,2.500,31.81,0.00260,...,0.00013,0.2,0.00662,0.02387,0.00000,0.0,0.0,0.0,0.00675,0.0
14,Mackerels,Regular,4.26664,0.10572,0.64168,0.00748,0.06500,1.090,10.31,0.07085,...,0.02539,0.2,0.13403,0.46527,0.00000,0.0,0.0,0.0,0.15942,0.0
13,Other offshore predators,Regular,4.57175,0.25134,0.18473,0.00259,0.29000,1.870,7.44,0.54230,...,0.44212,0.2,0.43152,1.18378,0.00000,0.0,0.0,0.0,0.87364,0.0
12,Blackfin tuna,Regular,4.19564,0.18706,0.95000,0.00232,0.00520,1.850,9.89,0.00962,...,0.00048,0.2,0.01029,0.03152,0.00000,0.0,0.0,0.0,0.01077,0.0
11,Bigeye,Regular,4.50223,0.10000,0.76947,0.00057,0.00168,1.759,17.59,0.00295,...,0.00068,0.2,0.00589,0.02062,0.00000,0.0,0.0,0.0,0.00657,0.0
10,Albacore,Regular,4.58489,0.10000,0.88807,0.00291,0.00970,0.780,7.80,0.00757,...,0.00085,0.2,0.01514,0.05298,0.00000,0.0,0.0,0.0,0.01599,0.0
9,Skipjack,Regular,4.84840,0.09995,0.69496,0.00478,0.01194,1.960,19.61,0.02341,...,0.00714,0.2,0.04684,0.16397,0.00000,0.0,0.0,0.0,0.05399,0.0
8,Yellowfin,Regular,4.85886,0.12878,0.95000,0.00818,0.00586,2.000,15.53,0.01171,...,0.00059,0.2,0.01819,0.06106,0.00000,0.0,0.0,0.0,0.01878,0.0
7,Billfishes,Regular,4.36535,0.10000,0.95000,0.00121,0.00987,0.460,4.60,0.00454,...,0.00023,0.2,0.00908,0.03178,0.00000,0.0,0.0,0.0,0.00931,0.0
6,Swordfish,Regular,4.71001,0.06968,0.91142,0.00015,0.00700,0.370,5.31,0.00259,...,0.00023,0.2,0.00743,0.02715,0.00000,0.0,0.0,0.0,0.00766,0.0
5,Shallow-diving cetaceans,Regular,4.75667,0.00370,0.79593,0.00003,0.03362,0.050,13.50,0.00168,...,0.00034,0.2,0.09078,0.36143,0.00000,0.0,0.0,0.0,0.09112,0.0
4,Killer whales,Regular,4.75240,0.00207,0.32155,0.00001,0.00158,0.020,9.64,0.00003,...,0.00002,0.2,0.00305,0.01217,0.00000,0.0,0.0,0.0,0.00307,0.0
3,Deep-diving whales,Regular,5.12650,0.00735,0.00000,0.00000,0.01454,0.040,5.44,0.00058,...,0.00058,0.2,0.01582,0.06268,0.00000,0.0,0.0,0.0,0.01640,0.0
2,Baleen whales,Regular,4.30301,0.00328,0.00000,0.00000,0.02513,0.040,12.19,0.00101,...,0.00101,0.2,0.06126,0.24403,0.00000,0.0,0.0,0.0,0.06226,0.0
1,Seabirds,Regular,4.48557,0.00176,0.44659,0.00000,0.00020,0.130,73.69,0.00003,...,0.00001,0.2,0.00295,0.01176,0.00000,0.0,0.0,0.0,0.00296,0.0

In [154]:
# groups_df[['egestion', 'respiration', 'biomass_accum', 'emigration', 'immigration', 'net_migration', 'M0']] = np.nan
groups_df[['M0', 'respiration', 'egestion', 'biomass_accum', 'gs', 'ee']] = np.nan
# groups_df[['M0', 'respiration', 'egestion', 'biomass_accum']] = np.nan

groups_df = apply_ecopath_defaults(groups_df, model.get_DC(), det_fate=model._det_fate, zero_biomass_accum=False, default_gs=False).round(6)
groups_df

,group_name,trophic_info,tl,ge,ee,catch,biomass,pb,qb,p,...,M0,gs,egestion,respiration,biomass_accum,emigration,immigration,net_migration,flow_to_det,detritus_import
group_seq,,,,,,,,,,,,,,,,,,,,,
32,diet_import,Import,1.000000,1.000000,1.0,0.000000,1.000000,84.566940,84.566940,84.566940,...,0.0,0.0,0.0,0.0,-0.000000,0.0,0.0,0.0,0.0,0.0
31,Detritus,DET,1.000000,1.000000,1.0,0.000000,15.075000,108.962906,108.962906,1642.615813,...,0.0,0.0,0.0,0.0,491.837442,0.0,0.0,0.0,0.0,0.0
30,Phytoplankton,PP,1.000000,1.000000,NaN,0.000000,32.000000,42.799998,42.799998,1369.599930,...,NaN,0.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN,0.0
29,Large zooplankton,Regular,3.005970,0.300000,NaN,0.000000,9.636000,8.700000,29.000000,83.833200,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
28,Small zooplankton,Regular,2.003012,0.299827,NaN,0.000000,40.000000,17.300000,57.700000,692.000000,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
27,Large squids,Regular,4.398368,0.290038,NaN,0.000007,0.177088,4.600001,15.860002,0.814605,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
26,Small squids,Regular,3.860465,0.300055,NaN,0.000000,1.157443,5.500000,18.329999,6.365936,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
25,Other turtles,Regular,3.504491,0.042846,NaN,0.000035,0.000767,0.149935,3.499348,0.000115,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
24,Leatherback turtle,Regular,3.985911,0.042649,NaN,0.000006,0.000569,0.149385,3.502636,0.000085,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
23,Large mesopelagics,Regular,4.016387,0.100000,NaN,0.000000,10.833000,0.355000,3.550000,3.845715,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
22,Small mesopelagics,Regular,3.054162,0.250667,NaN,0.000000,8.724072,3.760000,14.999999,32.802509,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
21,Small coastal pelagics,Regular,2.959125,0.239071,NaN,0.005799,0.244000,3.500000,14.640000,0.854000,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
20,Small offshore pelagics,Regular,2.958434,0.245902,NaN,0.000000,7.394000,3.600000,14.640000,26.618400,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
19,Coastal predators,Regular,3.604092,0.099723,NaN,0.012023,1.257362,0.719999,7.219997,0.905300,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
18,Flyingfish,Regular,3.029227,0.161551,NaN,0.002739,0.208249,4.000010,24.760052,0.832998,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
17,Pelagic sharks,Regular,4.756566,0.040001,NaN,0.002837,0.011605,0.400000,9.999655,0.004642,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
16,Dolphinfish,Regular,4.438981,0.236000,NaN,0.003606,0.027800,4.720000,20.000000,0.131216,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
15,Wahoo,Regular,4.806367,0.078578,NaN,0.000818,0.001040,2.500000,31.815385,0.002600,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
14,Mackerels,Regular,4.266637,0.105723,NaN,0.007475,0.065000,1.090000,10.310000,0.070850,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
13,Other offshore predators,Regular,4.571749,0.251344,NaN,0.002585,0.290000,1.870000,7.440000,0.542300,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
12,Blackfin tuna,Regular,4.195638,0.187050,NaN,0.002319,0.005200,1.850000,9.890385,0.009620,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
11,Bigeye,Regular,4.502232,0.099990,NaN,0.000569,0.001675,1.758806,17.589851,0.002946,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
10,Albacore,Regular,4.584893,0.099999,NaN,0.002911,0.009704,0.779988,7.799979,0.007569,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
9,Skipjack,Regular,4.848404,0.099948,NaN,0.004778,0.011944,1.959980,19.610013,0.023410,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
8,Yellowfin,Regular,4.858855,0.128786,NaN,0.008176,0.005857,2.000171,15.530989,0.011715,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
7,Billfishes,Regular,4.365351,0.100011,NaN,0.001210,0.009871,0.460034,4.599838,0.004541,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
6,Swordfish,Regular,4.710007,0.069680,NaN,0.000154,0.007000,0.370000,5.310000,0.002590,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
5,Shallow-diving cetaceans,Regular,4.756672,0.003704,NaN,0.000031,0.033621,0.049999,13.500015,0.001681,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
4,Killer whales,Regular,4.752395,0.002098,NaN,0.000010,0.001582,0.020228,9.639697,0.000032,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
3,Deep-diving whales,Regular,5.126501,0.007347,NaN,0.000000,0.014536,0.039970,5.440011,0.000581,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
2,Baleen whales,Regular,4.303012,0.003281,NaN,0.000000,0.025127,0.039997,12.189995,0.001005,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0
1,Seabirds,Regular,4.485569,0.001764,NaN,0.000000,0.000200,0.130000,73.690000,0.000026,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,0.0

In [158]:
apply_lim(groups_df.copy(), weight_flow=1.0, weight_guess=0.0).round(5)

,group_name,trophic_info,tl,ge,ee,catch,biomass,pb,qb,p,...,M0,gs,egestion,respiration,biomass_accum,emigration,immigration,net_migration,flow_to_det,detritus_import
group_seq,,,,,,,,,,,,,,,,,,,,,
32,diet_import,Import,1.00000,1.00000,1.00000,0.00000,1.00000,84.56694,84.56694,84.56694,...,0.00000,0.00000,0.00000,0.00000,-0.00000,0.0,0.0,0.0,0.00000,0.0
31,Detritus,DET,1.00000,1.00000,1.00000,0.00000,15.07500,108.96291,108.96291,1642.61581,...,0.00000,0.00000,0.00000,0.00000,491.83744,0.0,0.0,0.0,0.00000,0.0
30,Phytoplankton,PP,1.00000,1.00000,0.84209,0.00000,32.00000,42.80000,42.80000,1369.59993,...,216.27101,0.00000,0.00000,0.00000,0.00171,0.0,0.0,0.0,216.27101,0.0
29,Large zooplankton,Regular,3.00597,0.30000,0.95000,0.00000,9.63600,8.70000,29.00000,83.83320,...,4.19166,0.10000,27.94440,167.66640,66.86298,0.0,0.0,0.0,32.13606,0.0
28,Small zooplankton,Regular,2.00301,0.29983,0.66559,0.00000,40.00000,17.30000,57.70000,692.00000,...,231.41104,0.15559,359.10888,1256.89112,0.00000,0.0,0.0,0.0,590.51993,0.0
27,Large squids,Regular,4.39837,0.29004,0.35928,0.00001,0.17709,4.60000,15.86000,0.81460,...,0.52193,0.12195,0.34251,1.65150,0.00001,0.0,0.0,0.0,0.86444,0.0
26,Small squids,Regular,3.86046,0.30005,0.95000,0.00000,1.15744,5.50000,18.33000,6.36594,...,0.31830,0.10000,2.12159,12.72840,-0.00000,0.0,0.0,0.0,2.43989,0.0
25,Other turtles,Regular,3.50449,0.04285,0.95000,0.00003,0.00077,0.14994,3.49935,0.00012,...,0.00001,0.21270,0.00057,0.00200,-0.00000,0.0,0.0,0.0,0.00058,0.0
24,Leatherback turtle,Regular,3.98591,0.04265,0.95000,0.00001,0.00057,0.14938,3.50264,0.00008,...,0.00000,0.21274,0.00042,0.00148,-0.00000,0.0,0.0,0.0,0.00043,0.0
23,Large mesopelagics,Regular,4.01639,0.10000,0.17684,0.00000,10.83300,0.35500,3.55000,3.84572,...,3.16563,0.10000,3.84572,30.76572,0.00000,0.0,0.0,0.0,7.01135,0.0
22,Small mesopelagics,Regular,3.05416,0.25067,0.95000,0.00000,8.72407,3.76000,15.00000,32.80251,...,1.64013,0.14900,19.49781,78.56075,0.00000,0.0,0.0,0.0,21.13794,0.0
21,Small coastal pelagics,Regular,2.95912,0.23907,0.95000,0.00580,0.24400,3.50000,14.64000,0.85400,...,0.04270,0.10000,0.35722,2.36094,-0.00564,0.0,0.0,0.0,0.39992,0.0
20,Small offshore pelagics,Regular,2.95843,0.24590,0.33239,0.00000,7.39400,3.60000,14.64000,26.61840,...,17.77068,0.10000,10.82482,70.80494,0.00022,0.0,0.0,0.0,28.59549,0.0
19,Coastal predators,Regular,3.60409,0.09972,0.95000,0.01202,1.25736,0.72000,7.22000,0.90530,...,0.04526,0.10000,0.90781,7.26504,-0.00000,0.0,0.0,0.0,0.95308,0.0
18,Flyingfish,Regular,3.02923,0.16155,0.95000,0.00274,0.20825,4.00001,24.76005,0.83300,...,0.04165,0.10000,0.51563,3.80763,0.00000,0.0,0.0,0.0,0.55728,0.0
17,Pelagic sharks,Regular,4.75657,0.04000,0.95000,0.00284,0.01160,0.40000,9.99966,0.00464,...,0.00023,0.10000,0.01160,0.09980,-0.00019,0.0,0.0,0.0,0.01184,0.0
16,Dolphinfish,Regular,4.43898,0.23600,0.95000,0.00361,0.02780,4.72000,20.00000,0.13122,...,0.00656,0.10000,0.05560,0.36918,-0.00112,0.0,0.0,0.0,0.06216,0.0
15,Wahoo,Regular,4.80637,0.07858,0.95000,0.00082,0.00104,2.50000,31.81538,0.00260,...,0.00013,0.35000,0.01158,0.01891,-0.00000,0.0,0.0,0.0,0.01171,0.0
14,Mackerels,Regular,4.26664,0.10572,0.64181,0.00748,0.06500,1.09000,10.31000,0.07085,...,0.02538,0.10000,0.06702,0.53228,0.00001,0.0,0.0,0.0,0.09239,0.0
13,Other offshore predators,Regular,4.57175,0.25134,0.95000,0.00258,0.29000,1.87000,7.44000,0.54230,...,0.02711,0.10000,0.21576,1.39954,0.41501,0.0,0.0,0.0,0.24287,0.0
12,Blackfin tuna,Regular,4.19564,0.18705,0.95000,0.00232,0.00520,1.85000,9.89038,0.00962,...,0.00048,0.35000,0.01800,0.02381,-0.00000,0.0,0.0,0.0,0.01848,0.0
11,Bigeye,Regular,4.50223,0.09999,0.95000,0.00057,0.00168,1.75881,17.58985,0.00295,...,0.00015,0.35000,0.01031,0.01620,0.00053,0.0,0.0,0.0,0.01046,0.0
10,Albacore,Regular,4.58489,0.10000,0.95000,0.00291,0.00970,0.77999,7.79998,0.00757,...,0.00038,0.10000,0.00757,0.06055,0.00047,0.0,0.0,0.0,0.00795,0.0
9,Skipjack,Regular,4.84840,0.09995,0.69501,0.00478,0.01194,1.95998,19.61001,0.02341,...,0.00714,0.10000,0.02342,0.18739,0.00000,0.0,0.0,0.0,0.03056,0.0
8,Yellowfin,Regular,4.85886,0.12879,0.95000,0.00818,0.00586,2.00017,15.53099,0.01172,...,0.00059,0.10000,0.00910,0.07015,0.00000,0.0,0.0,0.0,0.00968,0.0
7,Billfishes,Regular,4.36535,0.10001,0.95000,0.00121,0.00987,0.46003,4.59984,0.00454,...,0.00023,0.35000,0.01589,0.02497,-0.00000,0.0,0.0,0.0,0.01612,0.0
6,Swordfish,Regular,4.71001,0.06968,0.95000,0.00015,0.00700,0.37000,5.31000,0.00259,...,0.00013,0.35000,0.01301,0.02157,0.00010,0.0,0.0,0.0,0.01314,0.0
5,Shallow-diving cetaceans,Regular,4.75667,0.00370,0.79664,0.00003,0.03362,0.05000,13.50002,0.00168,...,0.00034,0.10000,0.04539,0.40681,0.00000,0.0,0.0,0.0,0.04573,0.0
4,Killer whales,Regular,4.75240,0.00210,0.95000,0.00001,0.00158,0.02023,9.63970,0.00003,...,0.00000,0.35000,0.00534,0.00988,0.00002,0.0,0.0,0.0,0.00534,0.0
3,Deep-diving whales,Regular,5.12650,0.00735,0.95000,0.00000,0.01454,0.03997,5.44001,0.00058,...,0.00003,0.10000,0.00791,0.07059,0.00055,0.0,0.0,0.0,0.00794,0.0
2,Baleen whales,Regular,4.30301,0.00328,-0.00000,0.00000,0.02513,0.04000,12.19000,0.00100,...,0.00101,0.10000,0.03063,0.27466,-0.00000,0.0,0.0,0.0,0.03163,0.0
1,Seabirds,Regular,4.48557,0.00176,0.95000,0.00000,0.00020,0.13000,73.69000,0.00003,...,0.00000,0.35000,0.00516,0.00955,0.00001,0.0,0.0,0.0,0.00516,0.0

In [160]:
apply_lim(groups_df.copy(), weight_flow=0.0, weight_guess=1.0).round(5)

,group_name,trophic_info,tl,ge,ee,catch,biomass,pb,qb,p,...,M0,gs,egestion,respiration,biomass_accum,emigration,immigration,net_migration,flow_to_det,detritus_import
group_seq,,,,,,,,,,,,,,,,,,,,,
32,diet_import,Import,1.00000,1.00000,1.00000,0.00000,1.00000,84.56694,84.56694,84.56694,...,0.00000,0.00000,0.00000,0.00000,-0.00000,0.0,0.0,0.0,0.00000,0.0
31,Detritus,DET,1.00000,1.00000,1.00000,0.00000,15.07500,108.96291,108.96291,1642.61581,...,0.00000,0.00000,0.00000,0.00000,491.83744,0.0,0.0,0.0,0.00000,0.0
30,Phytoplankton,PP,1.00000,1.00000,0.90000,0.00000,32.00000,42.80000,42.80000,1369.59993,...,136.95999,0.00000,0.00000,0.00000,79.31272,0.0,0.0,0.0,136.95999,0.0
29,Large zooplankton,Regular,3.00597,0.30000,0.66667,0.00000,9.63600,8.70000,29.00000,83.83320,...,27.94440,0.15556,43.46907,152.14173,43.11024,0.0,0.0,0.0,71.41347,0.0
28,Small zooplankton,Regular,2.00301,0.29983,0.66647,0.00000,40.00000,17.30000,57.70000,692.00000,...,230.80000,0.15559,359.11111,1256.88889,0.61104,0.0,0.0,0.0,589.91111,0.0
27,Large squids,Regular,4.39837,0.29004,0.65522,0.00001,0.17709,4.60000,15.86000,0.81460,...,0.28086,0.15777,0.44311,1.55090,0.24108,0.0,0.0,0.0,0.72398,0.0
26,Small squids,Regular,3.86046,0.30005,0.66673,0.00000,1.15744,5.50000,18.33000,6.36594,...,2.12159,0.15554,3.30000,11.54999,-1.80330,0.0,0.0,0.0,5.42159,0.0
25,Other turtles,Regular,3.50449,0.04285,0.00000,0.00003,0.00077,0.14994,3.49935,0.00012,...,0.00011,0.21270,0.00057,0.00200,-0.00011,0.0,0.0,0.0,0.00069,0.0
24,Leatherback turtle,Regular,3.98591,0.04265,0.00000,0.00001,0.00057,0.14938,3.50264,0.00008,...,0.00008,0.21274,0.00042,0.00148,-0.00008,0.0,0.0,0.0,0.00051,0.0
23,Large mesopelagics,Regular,4.01639,0.10000,0.00000,0.00000,10.83300,0.35500,3.55000,3.84572,...,3.84572,0.20000,7.69143,26.92000,-0.68008,0.0,0.0,0.0,11.53714,0.0
22,Small mesopelagics,Regular,3.05416,0.25067,0.60106,0.00000,8.72407,3.76000,15.00000,32.80251,...,13.08611,0.16652,21.79079,76.26777,-11.44598,0.0,0.0,0.0,34.87690,0.0
21,Small coastal pelagics,Regular,2.95912,0.23907,0.58171,0.00580,0.24400,3.50000,14.64000,0.85400,...,0.35722,0.16910,0.60404,2.11412,-0.32016,0.0,0.0,0.0,0.96125,0.0
20,Small offshore pelagics,Regular,2.95843,0.24590,0.59333,0.00000,7.39400,3.60000,14.64000,26.61840,...,10.82482,0.16758,18.13995,63.48981,6.94608,0.0,0.0,0.0,28.96476,0.0
19,Coastal predators,Regular,3.60409,0.09972,0.00000,0.01202,1.25736,0.72000,7.22000,0.90530,...,0.90530,0.20006,1.81619,6.35666,-0.86004,0.0,0.0,0.0,2.72149,0.0
18,Flyingfish,Regular,3.02923,0.16155,0.38100,0.00274,0.20825,4.00001,24.76005,0.83300,...,0.51563,0.18632,0.96072,3.36253,-0.47398,0.0,0.0,0.0,1.47635,0.0
17,Pelagic sharks,Regular,4.75657,0.04000,0.00000,0.00284,0.01160,0.40000,9.99966,0.00464,...,0.00464,0.21333,0.02476,0.08665,-0.00459,0.0,0.0,0.0,0.02940,0.0
16,Dolphinfish,Regular,4.43898,0.23600,0.57627,0.00361,0.02780,4.72000,20.00000,0.13122,...,0.05560,0.16978,0.09440,0.33039,-0.05016,0.0,0.0,0.0,0.15000,0.0
15,Wahoo,Regular,4.80637,0.07858,0.00000,0.00082,0.00104,2.50000,31.81538,0.00260,...,0.00260,0.20476,0.00677,0.02371,-0.00247,0.0,0.0,0.0,0.00937,0.0
14,Mackerels,Regular,4.26664,0.10572,0.05413,0.00748,0.06500,1.09000,10.31000,0.07085,...,0.06702,0.19873,0.13318,0.46612,-0.04163,0.0,0.0,0.0,0.20019,0.0
13,Other offshore predators,Regular,4.57175,0.25134,0.60214,0.00258,0.29000,1.87000,7.44000,0.54230,...,0.21576,0.16637,0.35896,1.25634,0.22636,0.0,0.0,0.0,0.57472,0.0
12,Blackfin tuna,Regular,4.19564,0.18705,0.46538,0.00232,0.00520,1.85000,9.89038,0.00962,...,0.00514,0.18066,0.00929,0.03252,-0.00466,0.0,0.0,0.0,0.01443,0.0
11,Bigeye,Regular,4.50223,0.09999,-0.00010,0.00057,0.00168,1.75881,17.58985,0.00295,...,0.00295,0.20000,0.00589,0.02062,-0.00227,0.0,0.0,0.0,0.00884,0.0
10,Albacore,Regular,4.58489,0.10000,-0.00001,0.00291,0.00970,0.77999,7.79998,0.00757,...,0.00757,0.20000,0.01514,0.05298,-0.00672,0.0,0.0,0.0,0.02271,0.0
9,Skipjack,Regular,4.84840,0.09995,0.00000,0.00478,0.01194,1.95998,19.61001,0.02341,...,0.02341,0.20001,0.04685,0.16397,-0.01627,0.0,0.0,0.0,0.07026,0.0
8,Yellowfin,Regular,4.85886,0.12879,0.22352,0.00818,0.00586,2.00017,15.53099,0.01172,...,0.00910,0.19360,0.01761,0.06164,-0.00851,0.0,0.0,0.0,0.02671,0.0
7,Billfishes,Regular,4.36535,0.10001,0.00011,0.00121,0.00987,0.46003,4.59984,0.00454,...,0.00454,0.20000,0.00908,0.03178,-0.00431,0.0,0.0,0.0,0.01362,0.0
6,Swordfish,Regular,4.71001,0.06968,0.00000,0.00015,0.00700,0.37000,5.31000,0.00259,...,0.00259,0.20673,0.00768,0.02690,-0.00236,0.0,0.0,0.0,0.01027,0.0
5,Shallow-diving cetaceans,Regular,4.75667,0.00370,-0.00000,0.00003,0.03362,0.05000,13.50002,0.00168,...,0.00168,0.22139,0.10048,0.35172,-0.00134,0.0,0.0,0.0,0.10217,0.0
4,Killer whales,Regular,4.75240,0.00210,-0.00000,0.00001,0.00158,0.02023,9.63970,0.00003,...,0.00003,0.22137,0.00338,0.01184,-0.00001,0.0,0.0,0.0,0.00341,0.0
3,Deep-diving whales,Regular,5.12650,0.00735,-0.00000,0.00000,0.01454,0.03997,5.44001,0.00058,...,0.00058,0.22059,0.01744,0.06105,-0.00000,0.0,0.0,0.0,0.01802,0.0
2,Baleen whales,Regular,4.30301,0.00328,-0.00000,0.00000,0.02513,0.04000,12.19000,0.00100,...,0.00101,0.22140,0.06781,0.23748,-0.00000,0.0,0.0,0.0,0.06882,0.0
1,Seabirds,Regular,4.48557,0.00176,0.00000,0.00000,0.00020,0.13000,73.69000,0.00003,...,0.00003,0.22185,0.00327,0.01144,-0.00001,0.0,0.0,0.0,0.00330,0.0

In [162]:
apply_lim(groups_df.copy(), weight_flow=1.0, weight_guess=1.0).round(8)

,group_name,trophic_info,tl,ge,ee,catch,biomass,pb,qb,p,...,M0,gs,egestion,respiration,biomass_accum,emigration,immigration,net_migration,flow_to_det,detritus_import
group_seq,,,,,,,,,,,,,,,,,,,,,
32,diet_import,Import,1.000000,1.000000,1.000000,0.000000,1.000000,84.566940,84.566940,84.566940,...,0.000000,0.000000,0.000000,0.000000,-0.000000e+00,0.0,0.0,0.0,0.000000,0.0
31,Detritus,DET,1.000000,1.000000,1.000000,0.000000,15.075000,108.962906,108.962906,1642.615813,...,0.000000,0.000000,0.000000,0.000000,4.918374e+02,0.0,0.0,0.0,0.000000,0.0
30,Phytoplankton,PP,1.000000,1.000000,0.890873,0.000000,32.000000,42.799998,42.799998,1369.599930,...,149.459746,0.000000,0.000000,0.000000,6.681297e+01,0.0,0.0,0.0,149.459746,0.0
29,Large zooplankton,Regular,3.005970,0.300000,0.707952,0.000000,9.636000,8.700000,29.000000,83.833200,...,24.483340,0.104193,29.116083,166.494717,4.657130e+01,0.0,0.0,0.0,53.599423,0.0
28,Small zooplankton,Regular,2.003012,0.299827,0.666034,0.000000,40.000000,17.300000,57.700000,692.000000,...,231.104711,0.155593,359.109745,1256.890255,3.063326e-01,0.0,0.0,0.0,590.214457,0.0
27,Large squids,Regular,4.398368,0.290038,0.643162,0.000007,0.177088,4.600001,15.860002,0.814605,...,0.290682,0.105662,0.296763,1.697248,2.312571e-01,0.0,0.0,0.0,0.587445,0.0
26,Small squids,Regular,3.860465,0.300055,0.819044,0.000000,1.157443,5.500000,18.329999,6.365936,...,1.151956,0.104135,2.209312,12.640681,-8.336600e-01,0.0,0.0,0.0,3.361268,0.0
25,Other turtles,Regular,3.504491,0.042847,0.950000,0.000035,0.000767,0.149935,3.499348,0.000115,...,0.000006,0.212701,0.000571,0.001998,-4.750000e-06,0.0,0.0,0.0,0.000577,0.0
24,Leatherback turtle,Regular,3.985911,0.042649,0.950000,0.000006,0.000569,0.149385,3.502636,0.000085,...,0.000004,0.212745,0.000424,0.001484,-4.250000e-06,0.0,0.0,0.0,0.000428,0.0
23,Large mesopelagics,Regular,4.016387,0.100000,0.100914,0.000000,10.833000,0.355000,3.550000,3.845715,...,3.457628,0.133900,5.149423,29.462012,-2.919946e-01,0.0,0.0,0.0,8.607051,0.0
22,Small mesopelagics,Regular,3.054162,0.250667,0.786368,0.000000,8.724072,3.760000,14.999999,32.802509,...,7.007665,0.111536,14.595688,83.462875,-5.367536e+00,0.0,0.0,0.0,21.603352,0.0
21,Small coastal pelagics,Regular,2.959125,0.239071,0.779443,0.005799,0.244000,3.500000,14.640000,0.854000,...,0.188356,0.113210,0.404403,2.313757,-1.512978e-01,0.0,0.0,0.0,0.592758,0.0
20,Small offshore pelagics,Regular,2.958434,0.245902,0.560179,0.000000,7.394000,3.600000,14.640000,26.618400,...,11.707320,0.112237,12.149454,69.480306,6.063574e+00,0.0,0.0,0.0,23.856775,0.0
19,Coastal predators,Regular,3.604092,0.099723,0.485472,0.012023,1.257362,0.719999,7.219997,0.905300,...,0.465802,0.134003,1.216504,6.956346,-4.205377e-01,0.0,0.0,0.0,1.682306,0.0
18,Flyingfish,Regular,3.029227,0.161551,0.676950,0.002739,0.208249,4.000010,24.760052,0.832998,...,0.269100,0.124801,0.643504,3.679754,-2.274502e-01,0.0,0.0,0.0,0.912604,0.0
17,Pelagic sharks,Regular,4.756566,0.040001,0.000000,0.002837,0.011605,0.400000,9.999655,0.004642,...,0.004642,0.142893,0.016582,0.094822,-4.595000e-03,0.0,0.0,0.0,0.021224,0.0
16,Dolphinfish,Regular,4.438981,0.236000,0.776445,0.003606,0.027800,4.720000,20.000000,0.131216,...,0.029334,0.113563,0.063141,0.361643,-2.389095e-02,0.0,0.0,0.0,0.092475,0.0
15,Wahoo,Regular,4.806367,0.078578,0.950000,0.000818,0.001040,2.500000,31.815385,0.002600,...,0.000130,0.350000,0.011581,0.018907,-1.000000e-06,0.0,0.0,0.0,0.011711,0.0
14,Mackerels,Regular,4.266637,0.105723,0.397787,0.007475,0.065000,1.090000,10.310000,0.070850,...,0.042667,0.133110,0.089204,0.510096,-1.727981e-02,0.0,0.0,0.0,0.131871,0.0
13,Other offshore predators,Regular,4.571749,0.251344,0.607291,0.002585,0.290000,1.870000,7.440000,0.542300,...,0.212966,0.111421,0.240402,1.374898,2.291539e-01,0.0,0.0,0.0,0.453368,0.0
12,Blackfin tuna,Regular,4.195638,0.187050,0.950000,0.002319,0.005200,1.850000,9.890385,0.009620,...,0.000481,0.350000,0.018000,0.023810,-0.000000e+00,0.0,0.0,0.0,0.018482,0.0
11,Bigeye,Regular,4.502232,0.099990,0.950000,0.000569,0.001675,1.758806,17.589851,0.002946,...,0.000147,0.350000,0.010312,0.016205,5.317000e-04,0.0,0.0,0.0,0.010459,0.0
10,Albacore,Regular,4.584893,0.099999,0.940500,0.002911,0.009704,0.779988,7.799979,0.007569,...,0.000450,0.134866,0.010208,0.057914,3.966400e-04,0.0,0.0,0.0,0.010658,0.0
9,Skipjack,Regular,4.848404,0.099948,0.396907,0.004778,0.011944,1.959980,19.610013,0.023410,...,0.014118,0.133970,0.031379,0.179433,-6.977410e-03,0.0,0.0,0.0,0.045497,0.0
8,Yellowfin,Regular,4.858855,0.128786,0.949990,0.008176,0.005857,2.000171,15.530989,0.011715,...,0.000586,0.130689,0.011888,0.067362,1.400000e-07,0.0,0.0,0.0,0.012474,0.0
7,Billfishes,Regular,4.365351,0.100011,0.950000,0.001210,0.009871,0.460034,4.599838,0.004541,...,0.000227,0.350000,0.015892,0.024972,-5.000000e-08,0.0,0.0,0.0,0.016119,0.0
6,Swordfish,Regular,4.710007,0.069680,0.950000,0.000154,0.007000,0.370000,5.310000,0.002590,...,0.000130,0.350000,0.013010,0.021570,1.005000e-04,0.0,0.0,0.0,0.013139,0.0
5,Shallow-diving cetaceans,Regular,4.756672,0.003704,0.000000,0.000031,0.033621,0.049999,13.500015,0.001681,...,0.001681,0.148252,0.067289,0.384914,-1.338000e-03,0.0,0.0,0.0,0.068970,0.0
4,Killer whales,Regular,4.752395,0.002098,0.950000,0.000010,0.001582,0.020228,9.639697,0.000032,...,0.000002,0.350000,0.005338,0.009881,2.040000e-05,0.0,0.0,0.0,0.005339,0.0
3,Deep-diving whales,Regular,5.126501,0.007347,-0.000000,0.000000,0.014536,0.039970,5.440011,0.000581,...,0.000581,0.147753,0.011684,0.066811,-0.000000e+00,0.0,0.0,0.0,0.012265,0.0
2,Baleen whales,Regular,4.303012,0.003281,-0.000000,0.000000,0.025127,0.039997,12.189995,0.001005,...,0.001005,0.148359,0.045442,0.259851,-0.000000e+00,0.0,0.0,0.0,0.046447,0.0
1,Seabirds,Regular,4.485569,0.001764,0.950000,0.000000,0.000200,0.130000,73.690000,0.000026,...,0.000001,0.350000,0.005158,0.009554,1.270000e-05,0.0,0.0,0.0,0.005160,0.0