In [1]:
import os
import sys

# Standard interactive replacement for the 'parent directory' hack
parent_dir = os.path.abspath(os.path.join(os.getcwd(), '..'))
sys.path.append(parent_dir)

import pandas as pd
import numpy as np
from tqdm import tqdm
from pathlib import Path

from PPRCalculator import PPRCalculator
from ModelData import ModelData

In [4]:
# print model number, LME, and country of all files:
ewe_dir = Path('../real_models/EwE_jsons')
model_files = sorted(ewe_dir.glob('*.json'))

balanced_models = []
not_balanced = []

for f in model_files:
    try:
        model_number = int(f.name.split('_')[0])
        self = PPRCalculator(model_number)
        balanced = self.is_model_balanced()[0]
        if int(self.get_model().lme) == 62:
            print(f'LME: {self.get_model().lme} | {f.name} | balanced: {balanced} |')
    except:
        continue

c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 5 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 37 (Shortfinned squid), 17 (Winter flounder), 16 (Witch flounder), 3 (Grey seals), 1 (Walrus).
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 2 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 5 (Sei whales), 4 (Brydes whales).
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 1 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 1 (Engraulidae).
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 8 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 29 (Invert-eat Bird), 25 (Capelin), 22 (Eulachon), 14 (Seabirds), 13 (Avian Predators), 10 (Adult Salmon), 2 (Resident Orca), 1 (Transient Orca).
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 2 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 9 (Dorado), 3 (Picudos).
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 10 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 44 (Phytoplankton), 33 (Oyster 1+), 32 (Oyster YOY), 29 (Non-piscivorous seabirds), 28 (Piscivorous birds), 17 (White perch adult), 12 (Menhaden adult), 7 (Weakfish Adult), 5 (Bluefish adult), 3 (Striped bass migratory).
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 6 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 6 (Tuna/billfish), 5 (Penguins), 4 (Seabirds), 3 (Seal), 2 (Baleen whale), 1 (Toothed whale).
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 1 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 9 (Sth Rock Lobster).
  warnings.warn(

LME: 62 | 433_433_BlackSea_(1955).json | balanced: True |
LME: 62 | 435_435_Black_Sea_(1990).json | balanced: True |

c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 1 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 28 (Phytoplankton).
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 4 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 30 (Farfantepenaeus californiensis (ADULTS)), 28 (Litopenaeus stylirostris (ADULTS)), 20 (Litopenaeus stylirostris (JUVENILES)), 19 (Farfantepenaeus californiensis (JUVENILES)).
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 14 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 25 (Other turtles), 24 (Leatherback turtle), 20 (Small offshore pelagics), 19 (Coastal predators), 17 (Pelagic sharks), 16 (Dolphinfish), 14 (Mackerels), 13 (Other offshore predators), 11 (Bigeye), 10 (Albacore), 7 (Billfishes), 4 (Killer whales), 3 (Deep-diving whales), 1 (Seabirds).
  warnings.warn(

LME: 62 | 468_468_BlackSea_(1990).json | balanced: True |

c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 4 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 29 (chinook juv.), 27 (coho juv.), 25 (chum), 24 (pink).
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 2 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 25 (chum), 24 (pink).
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 2 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 25 (chum), 24 (pink).
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 7 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 42 (Benthic algae), 40 (Phytoplankton), 39 (Herbivorous zooplankton), 15 (Carnivorous zooplankton), 5 (Sea lions), 4 (Birds), 2 (Toothed cetaceans).
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 3 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 23 (Turf algae_LB), 6 (Hawksbills), 4 (Rays).
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 5 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 37 (Short finned squid), 17 (Winter flounder), 15 (Yellowtail flounder), 3 (Grey seals), 1 (Walrusses).
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 2 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 34 (Macroalgae), 26 (cephalopods).
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 2 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 40 (LCsharks), 25 (juv Menhaden).
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 2 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 62 (oceanproduction), 61 (climateforcer).
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 1 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 3 (Birds).
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 1 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 4 (Birds).
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 3 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 32 (crustaces comm), 30 (cephalopodes non-comm), 1 (orque).
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 3 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 32 (crustaces comm), 30 (cephalopodes non-comm), 1 (orque).
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 4 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 36 (Baleen whales), 6 (Predatory echinoderms), 5 (Other benthos), 4 (Worms).
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 5 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 50 (Macrophytes), 16 (Eulachon), 9 (Small squid), 6 (Transient salmon), 1 (Sea Otters).
  warnings.warn(

LME: 62 | 691_691_Black_Sea_(1960).json | balanced: True |
LME: 62 | 692_692_Black_Sea_(1980).json | balanced: True |
LME: 62 | 693_693_Black_Sea_(1988).json | balanced: True |

c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 1 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 8 (Mesopelagics).
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 3 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 28 (Pinnipeds), 25 (Sharks- coastal), 8 (Mesopelagics).
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 1 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 30 (Sea Birds).
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 3 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 40 (birds), 39 (turtles), 6 (Octopus).
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 1 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 44 (Sessile epibenthos).
  warnings.warn(

In [5]:
# All real models where model number > 10000 (model number = 2nd token in filename)
ewe_dir = Path('../real_models/new_EwE_jsons')
models_over_10000 = [
    f.name for f in sorted(ewe_dir.glob('*.json'))
    if ModelData._parse_filename(f.stem)[0] > 10000
]
for i, name in enumerate(models_over_10000):
    print(i, name)

0 13_10013_Humboldt_Current_(1980).json
1 13_11013_Humboldt_Current_(1995-2004).json
2 36_10036_Northern_South_China_Sea_(1970s).json
3 36_11036_Northern_South_China_Sea_(2000s).json
4 36_12036_Northern_South_China_Sea_Ecobase_(1970).json
5 47_10047_East_China_Sea_(1997).json
6 47_11047_East_China_Sea_(2018).json
7 48_10048_North_Yellow_Sea_(2019).json
8 48_11048_North_Yellow_Sea_(2019).json
9 48_12048_Southwestern_Yellow_Sea_(2008).json
10 49_10049_Kuroshio_Current_(2013).json
11 62_10062_Black_Sea_(1960-1969).json
12 62_11062_Black_Sea_(1980-1987).json
13 62_12062_Black_Sea_(1988-1994).json
14 62_13062_Black_Sea_(1995-2000).json
15 62_14062_Black_Sea_Ecobase_(1960-1969).json

### ecopath model comparison

In [7]:
model_path_new = f'../real_models/new_EwE_jsons/{models_over_10000[11]}'
model_path_new2 = f'../real_models/new_EwE_jsons/{models_over_10000[15]}'
model_path_orig = f'../real_models/EwE_jsons/691_691_Black_Sea_(1960).json'

model_new = ModelData(model_path_new)
model_new2 = ModelData(model_path_new2)
model_orig = ModelData(model_path_orig)
self_new = PPRCalculator.from_modeldata(model_new, underdetermined=True, zero_biomass_accum=False)
self_new2 = PPRCalculator.from_modeldata(model_new2, underdetermined=True, zero_biomass_accum=False)
self_orig = PPRCalculator.from_modeldata(model_orig, underdetermined=True, zero_biomass_accum=False)

df_new = self_new.get_groups_df()
df_new2 = self_new.get_groups_df()
df_orig = self_orig.get_groups_df()
df_orig.columns

Index(['group_name', 'trophic_info', 'taxon_descr', 'tl', 'ge', 'ee', 'catch',
       'biomass', 'pb', 'qb', 'p', 'q', 'predation', 'M0', 'gs', 'egestion',
       'respiration', 'biomass_accum', 'emigration', 'immigration',
       'net_migration', 'flow_to_det', 'detritus_import', 'det_export'],
      dtype='object')

In [ ]:
# self = self_orig
self = self_new

In [11]:
col = 'biomass_accum'
bool(np.all(np.isclose(df_orig[col] - df_new[col], 0)))
# df_new[col]

True

In [60]:
# model_path = '../real_models/EwE_jsons/227_227_Iceland_(1950).json'
# model_path = '../real_models/ToyModels/900_900_Multi_DET_Toy_(2026).json'
# model_path = '../real_models/EwE_jsons/68_68_Icelandic_shelf_(1997).json'
# model_path = '../real_models/EwE_jsons/410_410_North_South_of_China_Sea_(1970).json'
model_path = f'../real_models/EwE_jsons/691_691_Black_Sea_(1960).json'
model_path = f'../real_models/EwE_jsons/693_693_Black_Sea_(1988).json'
# model_path = f'../real_models/EwE_jsons/433_433_BlackSea_(1955).json'
# model_path = f'../real_models/new_EwE_jsons/{models_over_10000[4]}'

# model_path = f'../real_models/new_EwE_jsons/{models_over_10000[11]}'
# model_path = f'../real_models/new_EwE_jsons/{models_over_10000[15]}'

model = ModelData(model_path)
self = PPRCalculator.from_modeldata(model, underdetermined=False, zero_biomass_accum=False, default_gs=False)
self.get_groups_df().round(5)

,group_name,trophic_info,taxon_descr,tl,ge,ee,catch,biomass,pb,qb,...,gs,egestion,respiration,biomass_accum,emigration,immigration,net_migration,flow_to_det,detritus_import,det_export
group_seq,,,,,,,,,,,,,,,,,,,,,
11,diet_import,Import,NaN,1.0,1.00000,1.00000,0.0000,1.00000,0.00000,0.00000,...,0.0,0.00000,0.00000,0.00000,0.0,0.0,0.0,0.00000,0.0,0.0
10,Detritus,DET,None,NaN,1.00000,1.00000,0.0000,80.00000,6.28045,6.28045,...,0.0,0.00000,0.00000,410.29453,0.0,0.0,0.0,0.00000,0.0,0.0
9,Phytoplankton,PP,None,NaN,1.00000,0.22996,0.0000,1.95000,291.00000,291.00000,...,0.0,0.00000,0.00000,0.00000,0.0,0.0,0.0,436.95971,0.0,0.0
8,Noctiluca,Regular,None,NaN,0.20166,0.00000,0.0000,0.73600,7.30000,36.20000,...,0.2,5.32864,15.94176,0.00000,0.0,0.0,0.0,10.70144,0.0,0.0
7,Zooplankton,Regular,None,NaN,0.12754,0.99211,0.0000,0.54000,44.00000,345.00000,...,0.2,37.26000,125.28000,0.00000,0.0,0.0,0.0,37.44742,0.0,0.0
6,Mnemiopsis,Regular,None,NaN,0.37671,0.00000,0.0000,0.82100,11.00000,29.20000,...,0.2,4.79464,10.14756,0.00000,0.0,0.0,0.0,13.82564,0.0,0.0
5,Aurelia,Regular,None,NaN,0.37671,0.00000,0.0000,0.11200,11.00000,29.20000,...,0.2,0.65408,1.38432,0.00000,0.0,0.0,0.0,1.88608,0.0,0.0
4,Small pelagic fish,Regular,None,NaN,0.13636,0.61823,0.1700,0.53800,1.50000,11.00000,...,0.2,1.18360,3.92740,0.00000,0.0,0.0,0.0,1.49169,0.0,0.0
3,Demersal fish,Regular,None,NaN,0.42000,0.79079,0.0241,0.12100,0.63000,1.50000,...,0.2,0.03630,0.06897,0.00000,0.0,0.0,0.0,0.05225,0.0,0.0
2,Piscivorous fish,Regular,None,NaN,0.11000,0.99500,0.0163,0.03152,0.55000,5.00000,...,0.2,0.03152,0.10874,0.00000,0.0,0.0,0.0,0.03161,0.0,0.0
1,Dolphins,Regular,None,NaN,0.01842,0.28600,0.0010,0.00999,0.35000,19.00000,...,0.2,0.03796,0.14835,0.00000,0.0,0.0,0.0,0.04046,0.0,0.0

In [47]:
# PPRCalculator.rename_results(self.get_DC(), self.seq2name).round(5)
PPRCalculator.rename_results(self.get_det_fate(), self.seq2name).round(5)
# self.get_DC().round(5)

                    Detritus
group_seq
diet_import              0.0
Detritus                 1.0
Phytoplankton            1.0
Noctiluca                1.0
Zooplankton              1.0
Aurelia                  1.0
Small pelagic fish       1.0
Demersal fish            1.0
Piscivorous fish         1.0
Dolphins                 1.0

In [61]:
balanced, p, q = self.is_model_balanced()
print(f'balanced: {balanced}')
groups_df = self.get_groups_df()
groups_df['p-p`'] = p - groups_df['p']
groups_df['q-q`'] = q - groups_df['q']
groups_df.round(5)

balanced: True

,group_name,trophic_info,taxon_descr,tl,ge,ee,catch,biomass,pb,qb,...,respiration,biomass_accum,emigration,immigration,net_migration,flow_to_det,detritus_import,det_export,p-p`,q-q`
group_seq,,,,,,,,,,,,,,,,,,,,,
11,diet_import,Import,NaN,1.0,1.00000,1.00000,0.0000,1.00000,0.00000,0.00000,...,0.00000,0.00000,0.0,0.0,0.0,0.00000,0.0,0.0,0.00000,0.00000
10,Detritus,DET,None,NaN,1.00000,1.00000,0.0000,80.00000,6.28045,6.28045,...,0.00000,410.29453,0.0,0.0,0.0,0.00000,0.0,0.0,0.00000,0.00000
9,Phytoplankton,PP,None,NaN,1.00000,0.22996,0.0000,1.95000,291.00000,291.00000,...,0.00000,0.00000,0.0,0.0,0.0,436.95971,0.0,0.0,-0.00001,-0.00001
8,Noctiluca,Regular,None,NaN,0.20166,0.00000,0.0000,0.73600,7.30000,36.20000,...,15.94176,0.00000,0.0,0.0,0.0,10.70144,0.0,0.0,0.00000,-0.00000
7,Zooplankton,Regular,None,NaN,0.12754,0.99211,0.0000,0.54000,44.00000,345.00000,...,125.28000,0.00000,0.0,0.0,0.0,37.44742,0.0,0.0,0.00000,0.00000
6,Mnemiopsis,Regular,None,NaN,0.37671,0.00000,0.0000,0.82100,11.00000,29.20000,...,10.14756,0.00000,0.0,0.0,0.0,13.82564,0.0,0.0,0.00000,0.00000
5,Aurelia,Regular,None,NaN,0.37671,0.00000,0.0000,0.11200,11.00000,29.20000,...,1.38432,0.00000,0.0,0.0,0.0,1.88608,0.0,0.0,0.00000,0.00000
4,Small pelagic fish,Regular,None,NaN,0.13636,0.61823,0.1700,0.53800,1.50000,11.00000,...,3.92740,0.00000,0.0,0.0,0.0,1.49169,0.0,0.0,-0.00000,-0.00000
3,Demersal fish,Regular,None,NaN,0.42000,0.79079,0.0241,0.12100,0.63000,1.50000,...,0.06897,0.00000,0.0,0.0,0.0,0.05225,0.0,0.0,0.00000,0.00000
2,Piscivorous fish,Regular,None,NaN,0.11000,0.99500,0.0163,0.03152,0.55000,5.00000,...,0.10874,0.00000,0.0,0.0,0.0,0.03161,0.0,0.0,-0.00000,-0.00000
1,Dolphins,Regular,None,NaN,0.01842,0.28600,0.0010,0.00999,0.35000,19.00000,...,0.14835,0.00000,0.0,0.0,0.0,0.04046,0.0,0.0,-0.00000,0.00000

### model-specific tests

In [102]:
model_path = f'../real_models/new_EwE_jsons/{models_over_10000[15]}'

model = ModelData(model_path)
self = PPRCalculator.from_modeldata(model, underdetermined=True, zero_biomass_accum=False, weight_flow=0, weight_guess=10)
print(f'balanced: {self.is_model_balanced()[0]}')

self.get_groups_df()

balanced: True

,group_name,trophic_info,taxon_descr,tl,ge,ee,catch,biomass,pb,qb,...,gs,egestion,respiration,biomass_accum,emigration,immigration,net_migration,flow_to_det,detritus_import,det_export
group_seq,,,,,,,,,,,,,,,,,,,,,
10,diet_import,Import,NaN,1.0,1.000000,1.000000,0.000,1.00,0.000000,0.000000,...,0.0,0.0000,0.00000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0
9,Detritus,DET,None,NaN,1.000000,1.000000,0.000,80.00,2.390174,2.390174,...,0.0,0.0000,0.00000,98.942787,0.0,0.0,0.0,0.000000,0.0,0.0
8,Phytoplankton,PP,None,NaN,1.000000,0.541481,0.000,0.88,291.000000,291.000000,...,0.0,0.0000,0.00000,0.000000,0.0,0.0,0.0,117.417587,0.0,0.0
7,Noctiluca,Regular,None,NaN,0.201657,0.000000,0.000,0.09,7.300000,36.200000,...,0.2,0.6516,1.94940,0.000000,0.0,0.0,0.0,1.308600,0.0,0.0
6,Zooplankton,Regular,None,NaN,0.127536,0.108185,0.000,0.66,44.000000,345.000000,...,0.2,45.5400,153.12001,0.000000,0.0,0.0,0.0,71.438300,0.0,0.0
5,Aurelia,Regular,None,NaN,0.376712,0.000000,0.000,0.03,11.000000,29.200000,...,0.2,0.1752,0.37080,0.000000,0.0,0.0,0.0,0.505200,0.0,0.0
4,Small pelagic fish,Regular,None,NaN,0.136364,0.924167,0.020,0.20,1.500000,11.000000,...,0.2,0.4400,1.46000,0.000000,0.0,0.0,0.0,0.462750,0.0,0.0
3,Demersal fish,Regular,None,NaN,0.420000,0.811111,0.000,0.05,0.630000,1.500000,...,0.2,0.0150,0.02850,0.000000,0.0,0.0,0.0,0.020950,0.0,0.0
2,Piscivorous fish,Regular,None,NaN,0.110000,0.995455,0.010,0.02,0.550000,5.000000,...,0.2,0.0200,0.06900,0.000000,0.0,0.0,0.0,0.020050,0.0,0.0
1,Dolphins,Regular,None,NaN,0.018421,0.285714,0.001,0.01,0.350000,19.000000,...,0.2,0.0380,0.14850,0.000000,0.0,0.0,0.0,0.040500,0.0,0.0

In [103]:
sppr, sppr_det = self._sample_SPPR_new_forced_balance(TE_option='TE')
sppr

c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\PPRCalculator.py:1945: RuntimeWarning: 2 group(s) have TE=0 because EE=0 (M0=p): 7 (Noctiluca), 5 (Aurelia). Their consumed PP is re-credited to detritus (fix_EE_0_cases=True) so the TE SPPR stays PP-balanced.
  warnings.warn(

          10            9             8
10  1.000000      0.000000      0.000000
9   0.000000      0.979012      0.000000
8   0.000000      0.000000      1.000000
7   0.000000      0.000000      0.000000
6   0.000000     28.382215     43.486008
5   0.000000      0.000000      0.000000
4   0.000000    225.215080    345.064845
3   0.000000    352.538962    537.963573
2   3.652968   1234.055226   1890.766265
1   3.470319  46047.457067  70512.555398

In [114]:
sppr, A, L = self.SPPR_new(TE=None, TE_option='TE', collapse_det=None, fix_EE_0_cases=True, det_collapse_mode='never')
sppr, A, L = PPRCalculator.rename_results([sppr, A, L], self.seq2name)
print(self.is_model_balanced()[0])
print(self.get_PPR(sppr, only_inner=True, only_pp=False).sum(axis=1))
print(self.get_PPR(sppr, only_inner=True, only_pp=False).rename(columns=self.seq2name))
print(f'balanced: {self.is_sppr_balanced(sppr)}')
sppr.round(5)
# sppr.round(5).sum(axis=1)

True
catch    159.21382
dtype: float64
       Phytoplankton   Detritus
catch      96.321515  62.892305
balanced: (True, np.float64(256.12), np.float64(256.11998410610073))

c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\PPRCalculator.py:1945: RuntimeWarning: 2 group(s) have TE=0 because EE=0 (M0=p): 7 (Noctiluca), 5 (Aurelia). Their consumed PP is re-credited to detritus (fix_EE_0_cases=True) so the TE SPPR stays PP-balanced.
  warnings.warn(

                    diet_import     Detritus  Phytoplankton
diet_import             1.00000      0.00000        0.00000
Detritus                0.00000      0.97901        0.00000
Phytoplankton           0.00000      0.00000        1.00000
Noctiluca               0.00000      0.00000        0.00000
Zooplankton             0.00000     28.38221       43.48601
Aurelia                 0.00000      0.00000        0.00000
Small pelagic fish      0.00000    225.21506      345.06484
Demersal fish           0.00000    352.53893      537.96357
Piscivorous fish        3.65297   1234.05510     1890.76627
Dolphins                3.47032  46047.45249    70512.55540

In [112]:
sppr, A, L = self.SPPR_2015(only_pp_det=True)
sppr, A, L = PPRCalculator.rename_results([sppr, A, L], self.seq2name)
print(self.is_model_balanced()[0])
print(self.get_PPR(sppr, only_inner=True, only_pp=False).sum(axis=1))
print(self.get_PPR(sppr, only_inner=True, only_pp=False).rename(columns=self.seq2name))
print(f'balanced: {self.is_sppr_balanced(sppr)}')
sppr.round(5)
sppr.round(5).sum(axis=1)

True
catch    135.769348
dtype: float64
       Phytoplankton
catch     135.769348
balanced: (False, np.float64(256.12), np.float64(196.56654709793452))

group_seq
diet_import               1.00000
Detritus                  0.61406
Phytoplankton             1.00000
Noctiluca                 0.00000
Zooplankton              61.28813
Aurelia                   0.00000
Small pelagic fish      486.32610
Demersal fish           759.08596
Piscivorous fish       2668.45351
Dolphins              99398.29081
dtype: float64

In [25]:
# sppr, A, L = self.SPPR_EwE(TE_option='TE', silent=False)
# sppr, A, L = PPRCalculator.rename_results([sppr, A, L], self.seq2name)
# print(self.is_model_balanced()[0])
# print(self.get_PPR(sppr, only_inner=True).sum(axis=1))
# print(f'balanced: {self.is_sppr_balanced(sppr)}')
# sppr.round(3)

In [29]:
# sppr = self.SPPR_1995(global_TE=0.1)
# sppr = self.SPPR_1995(global_TE='mean')
# sppr, A, L = self.SPPR_EwE_Ido(TE_option='TE', use_EE=False)
# sppr,  = PPRCalculator.rename_results([sppr], self.seq2name)
# print(self.is_model_balanced()[0])
# print(self.get_PPR(sppr, only_inner=True).sum(axis=1))
# print(f'balanced: {self.is_sppr_balanced(sppr)}')
# sppr.round(3)

### cross-models tests

In [4]:
# Pipeline: build a summary DataFrame over every model in new_EwE_jsons
ewe_dir = Path('../real_models/EwE_jsons')
model_files = sorted(ewe_dir.glob('*.json'))

balanced_models = []
not_balanced = []

for f in tqdm(model_files):
    try:
        model = ModelData(str(f))
        self = PPRCalculator.from_modeldata(model, underdetermined=True, zero_biomass_accum=False)
        balanced = self.is_model_balanced()[0]
        # print(f'{f.name} - balanced: {balanced}')

        if balanced:
            balanced_models.append(f.name)
        else:
            not_balanced.append(f.name)

    except:
        continue

  0%|          | 0/230 [00:00<?, ?it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 5 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 37 (Shortfinned squid), 17 (Winter flounder), 16 (Witch flounder), 3 (Grey seals), 1 (Walrus).
  warnings.warn(
  3%|▎         | 6/230 [00:00<00:17, 13.15it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 2 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 5 (Sei whales), 4 (Brydes whales).
  warnings.warn(
 13%|█▎        | 30/230 [00:02<00:11, 17.24it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 1 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 1 (Engraulidae).
  warnings.warn(
 17%|█▋        | 38/230 [00:02<00:10, 17.85it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 8 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 29 (Invert-eat Bird), 25 (Capelin), 22 (Eulachon), 14 (Seabirds), 13 (Avian Predators), 10 (Adult Salmon), 2 (Resident Orca), 1 (Transient Orca).
  warnings.warn(
 20%|██        | 47/230 [00:03<00:11, 16.25it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 2 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 9 (Dorado), 3 (Picudos).
  warnings.warn(
 25%|██▍       | 57/230 [00:03<00:10, 16.21it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 10 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 44 (Phytoplankton), 33 (Oyster 1+), 32 (Oyster YOY), 29 (Non-piscivorous seabirds), 28 (Piscivorous birds), 17 (White perch adult), 12 (Menhaden adult), 7 (Weakfish Adult), 5 (Bluefish adult), 3 (Striped bass migratory).
  warnings.warn(
 27%|██▋       | 63/230 [00:04<00:15, 10.61it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 6 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 6 (Tuna/billfish), 5 (Penguins), 4 (Seabirds), 3 (Seal), 2 (Baleen whale), 1 (Toothed whale).
  warnings.warn(
 33%|███▎      | 75/230 [00:05<00:11, 13.22it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 1 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 9 (Sth Rock Lobster).
  warnings.warn(
 37%|███▋      | 84/230 [00:05<00:09, 15.30it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 1 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 28 (Phytoplankton).
  warnings.warn(
 38%|███▊      | 88/230 [00:06<00:11, 12.26it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 4 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 30 (Farfantepenaeus californiensis (ADULTS)), 28 (Litopenaeus stylirostris (ADULTS)), 20 (Litopenaeus stylirostris (JUVENILES)), 19 (Farfantepenaeus californiensis (JUVENILES)).
  warnings.warn(
 40%|████      | 92/230 [00:06<00:14,  9.85it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 14 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 25 (Other turtles), 24 (Leatherback turtle), 20 (Small offshore pelagics), 19 (Coastal predators), 17 (Pelagic sharks), 16 (Dolphinfish), 14 (Mackerels), 13 (Other offshore predators), 11 (Bigeye), 10 (Albacore), 7 (Billfishes), 4 (Killer whales), 3 (Deep-diving whales), 1 (Seabirds).
  warnings.warn(
 44%|████▍     | 102/230 [00:07<00:11, 11.04it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 4 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 29 (chinook juv.), 27 (coho juv.), 25 (chum), 24 (pink).
  warnings.warn(
 45%|████▌     | 104/230 [00:07<00:11, 11.45it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 2 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 25 (chum), 24 (pink).
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 2 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 25 (chum), 24 (pink).
  warnings.warn(
 48%|████▊     | 110/230 [00:08<00:10, 11.05it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 7 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 42 (Benthic algae), 40 (Phytoplankton), 39 (Herbivorous zooplankton), 15 (Carnivorous zooplankton), 5 (Sea lions), 4 (Birds), 2 (Toothed cetaceans).
  warnings.warn(
 50%|█████     | 116/230 [00:08<00:11, 10.21it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 3 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 23 (Turf algae_LB), 6 (Hawksbills), 4 (Rays).
  warnings.warn(
 54%|█████▍    | 124/230 [00:09<00:09, 10.87it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 5 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 37 (Short finned squid), 17 (Winter flounder), 15 (Yellowtail flounder), 3 (Grey seals), 1 (Walrusses).
  warnings.warn(
 55%|█████▍    | 126/230 [00:09<00:09, 10.48it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 2 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 34 (Macroalgae), 26 (cephalopods).
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 2 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 40 (LCsharks), 25 (juv Menhaden).
  warnings.warn(
 56%|█████▌    | 128/230 [00:10<00:11,  9.24it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 2 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 62 (oceanproduction), 61 (climateforcer).
  warnings.warn(
 61%|██████    | 140/230 [00:11<00:08, 10.09it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 1 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 3 (Birds).
  warnings.warn(
 62%|██████▏   | 142/230 [00:11<00:09,  9.10it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 1 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 4 (Birds).
  warnings.warn(
 62%|██████▏   | 143/230 [00:11<00:10,  8.56it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 3 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 32 (crustaces comm), 30 (cephalopodes non-comm), 1 (orque).
  warnings.warn(
 63%|██████▎   | 144/230 [00:11<00:10,  8.32it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 3 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 32 (crustaces comm), 30 (cephalopodes non-comm), 1 (orque).
  warnings.warn(
 63%|██████▎   | 145/230 [00:12<00:10,  8.27it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 4 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 36 (Baleen whales), 6 (Predatory echinoderms), 5 (Other benthos), 4 (Worms).
  warnings.warn(
 66%|██████▌   | 151/230 [00:12<00:08,  8.89it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 5 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 50 (Macrophytes), 16 (Eulachon), 9 (Small squid), 6 (Transient salmon), 1 (Sea Otters).
  warnings.warn(
 71%|███████▏  | 164/230 [00:14<00:07,  8.82it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 1 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 8 (Mesopelagics).
  warnings.warn(
 72%|███████▏  | 165/230 [00:14<00:08,  7.74it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 3 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 28 (Pinnipeds), 25 (Sharks- coastal), 8 (Mesopelagics).
  warnings.warn(
 72%|███████▏  | 166/230 [00:14<00:08,  7.87it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 1 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 30 (Sea Birds).
  warnings.warn(
 74%|███████▍  | 170/230 [00:15<00:07,  8.15it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 1 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 2 (Seabirds).
  warnings.warn(
 75%|███████▍  | 172/230 [00:15<00:07,  7.59it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 3 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 4 (small coastal sharks), 3 (large coastal sharks), 1 (Seabirds).
  warnings.warn(
 78%|███████▊  | 179/230 [00:16<00:06,  7.93it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 2 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 11 (Hake juvenile), 10 (Hake adulte).
  warnings.warn(
 80%|████████  | 185/230 [00:17<00:05,  7.76it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 2 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 13 (juvéniles poiss), 10 (juvenile cephal).
  warnings.warn(
 86%|████████▌ | 197/230 [00:18<00:05,  6.55it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 1 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 3 (seabirds).
  warnings.warn(
 88%|████████▊ | 203/230 [00:19<00:04,  5.95it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 8 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 8 (Benthic invertebrate f. birds), 7 (Surface feeding birds), 6 (Pelag diving birds), 5 (Piscivore benthic bird), 4 (Otters), 3 (Whales), 2 (Harbour seals), 1 (Grey seals).
  warnings.warn(
 94%|█████████▍| 216/230 [00:22<00:02,  5.68it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 2 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 68 (Phytoplankton), 66 (Zooplankton).
  warnings.warn(
 94%|█████████▍| 217/230 [00:22<00:02,  5.05it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 4 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 18 (Small pelagic producers), 17 (Large pelagic producers), 16 (Other meso-zooplankton), 15 (Arctic cod Larvae).
  warnings.warn(
 99%|█████████▉| 228/230 [00:24<00:00,  6.43it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 3 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 40 (birds), 39 (turtles), 6 (Octopus).
  warnings.warn(
100%|█████████▉| 229/230 [00:24<00:00,  6.25it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 1 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 44 (Sessile epibenthos).
  warnings.warn(
100%|██████████| 230/230 [00:24<00:00,  9.31it/s]

In [13]:
# Pipeline: build a summary DataFrame over every model in new_EwE_jsons
ewe_dir = Path('../real_models/new_EwE_jsons')
model_files = sorted(ewe_dir.glob('*.json'))

def safe(fn):
    """Run fn() and return its result, or np.nan if it raises."""
    try:
        return fn()
    except Exception as e:
        return np.nan


rows = []
for f in tqdm(model_files):
    model = ModelData(str(f))
    try:
        self = PPRCalculator.from_modeldata(model, underdetermined=True, zero_biomass_accum=False)
    except:
        continue

    # SPPR_new TE_option='TE' (default collapse) -> also reused for (4)
    sppr_TE = safe(lambda: self.SPPR_new(TE=None, TE_option='TE')[0])
    # SPPR_new TE_option='TE' with collapse_det=True
    sppr_TE_collapse = safe(lambda: self.SPPR_new(TE=None, TE_option='TE', collapse_det=True)[0])
    # SPPR_new TE_option='GE'
    sppr_GE = safe(lambda: self.SPPR_new(TE=None, TE_option='GE')[0])
    sppr_TE_collapse = safe(lambda: self.SPPR_new(TE=None, TE_option='GE', collapse_det=True)[0])

    rows.append({
        'filename': f.name,                                                                        # (1)
        'n_detritus': len(self.get_DET_seq()),                                                     # (2)
        'model_balanced': self.is_model_balanced()[0],                                             # (3)
        'sppr_balanced_TE': safe(lambda: self.is_sppr_balanced(sppr_TE)[0]),                       # (4)
        'sppr_balanced_collapse_det_TE': safe(lambda: self.is_sppr_balanced(sppr_TE_collapse)[0]), # (5)
        'sppr_balanced_GE': safe(lambda: self.is_sppr_balanced(sppr_GE)[0]),                       # (6)
        'sppr_balanced_collapse_det_GE': safe(lambda: self.is_sppr_balanced(sppr_TE_collapse)[0]), # (7)
        'PPR2NPP_TE_only_pp': safe(lambda: self.get_PPR2NPP_ratio(sppr_TE, only_pp=True)),         # (8)
        'PPR2NPP_TE_all': safe(lambda: self.get_PPR2NPP_ratio(sppr_TE, only_pp=False)),            # (9)
        'PPR2NPP_GE_only_pp': safe(lambda: self.get_PPR2NPP_ratio(sppr_GE, only_pp=True)),         # (10)
        'PPR2NPP_GE_all': safe(lambda: self.get_PPR2NPP_ratio(sppr_GE, only_pp=False)),            # (11)
        'PPR2NPP_1995_TE0.1': safe(lambda: self.get_PPR2NPP_ratio(self.SPPR_1995(global_TE=0.1))),    # (12)
        'PPR2NPP_1995_TEmean': safe(lambda: self.get_PPR2NPP_ratio(self.SPPR_1995(global_TE='mean'))),# (13)
    })

results_df = pd.DataFrame(rows)
results_df

  0%|          | 0/11 [00:00<?, ?it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\PPRCalculator.py:1944: RuntimeWarning: 1 group(s) have TE=0 because EE=0 (M0=p): 14 (Sea lions). Their consumed PP is re-credited to detritus (fix_EE_0_cases=True) so the TE SPPR stays PP-balanced.
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\PPRCalculator.py:1944: RuntimeWarning: 1 group(s) have TE=0 because EE=0 (M0=p): 14 (Sea lions). Their consumed PP is re-credited to detritus (fix_EE_0_cases=True) so the TE SPPR stays PP-balanced.
  warnings.warn(
  9%|▉         | 1/11 [00:00<00:01,  7.47it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\PPRCalculator.py:1953: RuntimeWarning: 4 group(s) have TE=0 because EE=0 (M0=p): 33 (Cetaceans), 32 (Pinnipeds), 31 (Seabirds), 7 (Chrysaora plocamia). Their consumed PP is dropped, so the TE SPPR will not balance (multi-DET: re-credit not applied).
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\PPRCalculator.py:1953: RuntimeWarning: 4 group(s) have TE=0 because EE=0 (M0=p): 33 (Cetaceans), 32 (Pinnipeds), 31 (Seabirds), 7 (Chrysaora plocamia). Their consumed PP is dropped, so the TE SPPR will not balance (multi-DET: re-credit not applied).
  warnings.warn(
 18%|█▊        | 2/11 [00:00<00:03,  2.85it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\PPRCalculator.py:1969: RuntimeWarning: 2 group(s) have near-zero TE (0 < EE << 1): 36 (Other mammals), 34 (Seabirds). Their SPPR is near-singular (inherent to the TE method); the detritus SPPR may be inflated and is not corrected by fix_EE_0_cases.
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\PPRCalculator.py:1969: RuntimeWarning: 2 group(s) have near-zero TE (0 < EE << 1): 36 (Other mammals), 34 (Seabirds). Their SPPR is near-singular (inherent to the TE method); the detritus SPPR may be inflated and is not corrected by fix_EE_0_cases.
  warnings.warn(
 27%|██▋       | 3/11 [00:01<00:04,  1.72it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\PPRCalculator.py:1969: RuntimeWarning: 3 group(s) have near-zero TE (0 < EE << 1): 36 (Other mammals), 35 (Pinnipeds), 34 (Seabirds). Their SPPR is near-singular (inherent to the TE method); the detritus SPPR may be inflated and is not corrected by fix_EE_0_cases.
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\PPRCalculator.py:1969: RuntimeWarning: 3 group(s) have near-zero TE (0 < EE << 1): 36 (Other mammals), 35 (Pinnipeds), 34 (Seabirds). Their SPPR is near-singular (inherent to the TE method); the detritus SPPR may be inflated and is not corrected by fix_EE_0_cases.
  warnings.warn(
 36%|███▋      | 4/11 [00:02<00:04,  1.50it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\PPRCalculator.py:1969: RuntimeWarning: 2 group(s) have near-zero TE (0 < EE << 1): 36 (Other mammals), 34 (Seabirds). Their SPPR is near-singular (inherent to the TE method); the detritus SPPR may be inflated and is not corrected by fix_EE_0_cases.
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\PPRCalculator.py:1969: RuntimeWarning: 2 group(s) have near-zero TE (0 < EE << 1): 36 (Other mammals), 34 (Seabirds). Their SPPR is near-singular (inherent to the TE method); the detritus SPPR may be inflated and is not corrected by fix_EE_0_cases.
  warnings.warn(
 45%|████▌     | 5/11 [00:03<00:04,  1.35it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\PPRCalculator.py:1944: RuntimeWarning: 2 group(s) have TE=0 because EE=0 (M0=p): 23 (Marine mammals), 22 (Sharks). Their consumed PP is re-credited to detritus (fix_EE_0_cases=True) so the TE SPPR stays PP-balanced.
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\PPRCalculator.py:1944: RuntimeWarning: 2 group(s) have TE=0 because EE=0 (M0=p): 23 (Marine mammals), 22 (Sharks). Their consumed PP is re-credited to detritus (fix_EE_0_cases=True) so the TE SPPR stays PP-balanced.
  warnings.warn(
 55%|█████▍    | 6/11 [00:03<00:02,  1.78it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\PPRCalculator.py:1944: RuntimeWarning: 2 group(s) have TE=0 because EE=0 (M0=p): 23 (Marine mammals), 22 (Sharks). Their consumed PP is re-credited to detritus (fix_EE_0_cases=True) so the TE SPPR stays PP-balanced.
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\PPRCalculator.py:1944: RuntimeWarning: 2 group(s) have TE=0 because EE=0 (M0=p): 23 (Marine mammals), 22 (Sharks). Their consumed PP is re-credited to detritus (fix_EE_0_cases=True) so the TE SPPR stays PP-balanced.
  warnings.warn(
 64%|██████▎   | 7/11 [00:03<00:01,  2.22it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\PPRCalculator.py:1944: RuntimeWarning: 2 group(s) have TE=0 because EE=0 (M0=p): 4 (Hexagrammos otakii), 2 (Piscivores). Their consumed PP is re-credited to detritus (fix_EE_0_cases=True) so the TE SPPR stays PP-balanced.
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\PPRCalculator.py:1969: RuntimeWarning: 1 group(s) have near-zero TE (0 < EE << 1): 3 (Sebastes schlegelii). Their SPPR is near-singular (inherent to the TE method); the detritus SPPR may be inflated and is not corrected by fix_EE_0_cases.
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\PPRCalculator.py:1944: RuntimeWarning: 2 group(s) have TE=0 because EE=0 (M0=p): 4 (Hexagrammos otakii), 2 (Piscivores). Their consumed PP is re-credited to detritus (fix_EE_0_cases=True) so the TE SPPR stays PP-balanced.
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\PPRCalculator.py:1969: RuntimeWarning: 1 group(s) have near-zero TE (0 < EE << 1): 3 (Sebastes schlegelii). Their SPPR is near-singular (inherent to the TE method); the detritus SPPR may be inflated and is not corrected by fix_EE_0_cases.
  warnings.warn(
 73%|███████▎  | 8/11 [00:03<00:01,  2.66it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\PPRCalculator.py:1944: RuntimeWarning: 2 group(s) have TE=0 because EE=0 (M0=p): 4 (Hexagrammos otakii), 2 (Piscivores). Their consumed PP is re-credited to detritus (fix_EE_0_cases=True) so the TE SPPR stays PP-balanced.
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\PPRCalculator.py:1969: RuntimeWarning: 1 group(s) have near-zero TE (0 < EE << 1): 3 (Sebastes schlegelii). Their SPPR is near-singular (inherent to the TE method); the detritus SPPR may be inflated and is not corrected by fix_EE_0_cases.
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\PPRCalculator.py:1944: RuntimeWarning: 2 group(s) have TE=0 because EE=0 (M0=p): 4 (Hexagrammos otakii), 2 (Piscivores). Their consumed PP is re-credited to detritus (fix_EE_0_cases=True) so the TE SPPR stays PP-balanced.
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\PPRCalculator.py:1969: RuntimeWarning: 1 group(s) have near-zero TE (0 < EE << 1): 3 (Sebastes schlegelii). Their SPPR is near-singular (inherent to the TE method); the detritus SPPR may be inflated and is not corrected by fix_EE_0_cases.
  warnings.warn(
 82%|████████▏ | 9/11 [00:04<00:00,  3.03it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\PPRCalculator.py:1944: RuntimeWarning: 3 group(s) have TE=0 because EE=0 (M0=p): 3 (Gruiformes), 2 (Anseriformes), 1 (Charadriiformes). Their consumed PP is re-credited to detritus (fix_EE_0_cases=True) so the TE SPPR stays PP-balanced.
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\PPRCalculator.py:1944: RuntimeWarning: 3 group(s) have TE=0 because EE=0 (M0=p): 3 (Gruiformes), 2 (Anseriformes), 1 (Charadriiformes). Their consumed PP is re-credited to detritus (fix_EE_0_cases=True) so the TE SPPR stays PP-balanced.
  warnings.warn(
100%|██████████| 11/11 [00:04<00:00,  2.58it/s]

,filename,n_detritus,model_balanced,sppr_balanced_TE,sppr_balanced_collapse_det_TE,sppr_balanced_GE,sppr_balanced_collapse_det_GE,PPR2NPP_TE_only_pp,PPR2NPP_TE_all,PPR2NPP_GE_only_pp,PPR2NPP_GE_all,PPR2NPP_1995_TE0.1,PPR2NPP_1995_TEmean
0,13_10013_Humboldt_Current_(1980).json,1,True,True,True,True,True,0.037599,0.052465,0.007102,0.007567,0.053072,0.022330
1,13_11013_Humboldt_Current_(1995-2004).json,4,True,False,True,True,True,0.042612,0.042612,0.008036,-0.015321,0.018804,0.024769
2,36_10036_Northern_South_China_Sea_(1970s).json,1,True,True,True,True,True,0.036368,0.051911,0.000232,0.000522,0.001316,0.000995
3,36_11036_Northern_South_China_Sea_(2000s).json,1,True,True,True,True,True,0.006871,0.010442,0.000769,0.001428,0.004236,0.001090
4,36_12036_Northern_South_China_Sea_Ecobase_(197...,1,False,False,False,False,False,0.035161,0.051230,0.000282,0.000542,0.001560,0.000711
5,47_10047_East_China_Sea_(1997).json,1,True,True,True,True,True,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
6,47_11047_East_China_Sea_(2018).json,1,True,True,True,True,True,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7,48_10048_North_Yellow_Sea_(2019).json,1,True,True,True,True,True,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
8,48_11048_North_Yellow_Sea_(2019).json,1,True,True,True,True,True,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
9,48_12048_Southwestern_Yellow_Sea_(2008).json,1,True,True,True,True,True,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [12]:
results_df['PPR2NPP_TE_all'] / results_df['PPR2NPP_1995_TE0.1']

0        6.727376
1       35.675632
2    14719.707168
3      509.680328
4    17406.426488
5       27.111279
6        0.719737
7      471.597899
8     1336.113457
9        1.030785
dtype: float64