In [1]:
import os
import sys

# Standard interactive replacement for the 'parent directory' hack
parent_dir = os.path.abspath(os.path.join(os.getcwd(), '..'))
sys.path.append(parent_dir)

import pandas as pd
import numpy as np
from tqdm import tqdm
from pathlib import Path

from PPRCalculator import PPRCalculator
from ModelData import ModelData

In [2]:
# All real models where model number > 10000 (model number = 2nd token in filename)
ewe_dir = Path('../real_models/new_EwE_jsons')
models_over_10000 = [
    f.name for f in sorted(ewe_dir.glob('*.json'))
    if ModelData._parse_filename(f.stem)[0] > 10000
]
for i, name in enumerate(models_over_10000):
    print(i, name)

0 13_10013_Humboldt_Current_(1980).json
1 13_11013_Humboldt_Current_(1995-2004).json
2 36_10036_Northern_South_China_Sea_(1970s).json
3 36_11036_Northern_South_China_Sea_(2000s).json
4 36_12036_Northern_South_China_Sea_Ecobase_(1970).json
5 47_10047_East_China_Sea_(1997).json
6 47_11047_East_China_Sea_(2018).json
7 48_10048_North_Yellow_Sea_(2019).json
8 48_11048_North_Yellow_Sea_(2019).json
9 48_12048_Southwestern_Yellow_Sea_(2008).json
10 49_10049_Kuroshio_Current_(2013).json

### ecopath model comparison

In [21]:
model_path_new = f'../real_models/new_EwE_jsons/{models_over_10000[4]}'
model_path_orig = f'../real_models/EwE_jsons/410_410_North_South_of_China_Sea_(1970).json'

model_new = ModelData(model_path_new)
model_orig = ModelData(model_path_orig)
self_new = PPRCalculator.from_modeldata(model_new, underdetermined=True, zero_biomass_accum=False)
self_orig = PPRCalculator.from_modeldata(model_orig, underdetermined=True, zero_biomass_accum=False)

df_new = self_new.get_groups_df()
df_orig = self_orig.get_groups_df()
df_orig.columns

Index(['group_name', 'trophic_info', 'taxon_descr', 'tl', 'ge', 'ee', 'catch',
       'biomass', 'pb', 'qb', 'p', 'q', 'predation', 'M0', 'gs', 'egestion',
       'respiration', 'biomass_accum', 'emigration', 'immigration',
       'net_migration', 'flow_to_det', 'detritus_import'],
      dtype='object')

In [22]:
# self = self_orig
self = self_new

In [11]:
col = 'biomass_accum'
bool(np.all(np.isclose(df_orig[col] - df_new[col], 0)))
# df_new[col]

True

In [13]:
# model_path = '../real_models/EwE_jsons/227_227_Iceland_(1950).json'
# model_path = '../real_models/ToyModels/900_900_Multi_DET_Toy_(2026).json'
# model_path = '../real_models/EwE_jsons/68_68_Icelandic_shelf_(1997).json'
model_path = '../real_models/EwE_jsons/410_410_North_South_of_China_Sea_(1970).json'

# model_path = f'../real_models/new_EwE_jsons/{models_over_10000[4]}'

model = ModelData(model_path)
self = PPRCalculator.from_modeldata(model, underdetermined=True, zero_biomass_accum=False)
# self = PPRCalculator.from_modeldata(model, underdetermined=False, zero_biomass_accum=False)
self.get_groups_df()

,group_name,trophic_info,taxon_descr,tl,ge,ee,catch,biomass,pb,qb,...,M0,gs,egestion,respiration,biomass_accum,emigration,immigration,net_migration,flow_to_det,detritus_import
group_seq,,,,,,,,,,,,,,,,,,,,,
39,diet_import,Import,NaN,1.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0
38,Detritus,DET,None,NaN,1.000000,1.000000,0.000000,100.000000,1291.868683,1291.868683,...,0.000000,0.0,0.000000,0.000000,127035.389678,0.0,0.0,0.0,0.000000,0.0
37,Seaturtles,Regular,None,NaN,0.028571,0.503045,0.000010,0.000200,0.100000,3.500000,...,0.000010,0.2,0.000140,0.000540,0.000000,0.0,0.0,0.0,0.000150,0.0
36,Other mammals,Regular,None,NaN,0.010643,0.068125,0.000120,0.015800,0.112000,10.523000,...,0.001649,0.2,0.033253,0.131241,0.000000,0.0,0.0,0.0,0.034902,0.0
35,Pinnipeds,Regular,None,NaN,0.003047,0.679270,0.000140,0.004600,0.045000,14.768000,...,0.000066,0.2,0.013587,0.054139,0.000000,0.0,0.0,0.0,0.013653,0.0
34,Seabirds,Regular,None,NaN,0.000885,0.004618,0.000000,0.002198,0.060000,67.759000,...,0.000131,0.2,0.029787,0.119016,0.000000,0.0,0.0,0.0,0.029918,0.0
33,Pelagic sharks and rays,Regular,None,NaN,0.200000,0.500000,0.005042,0.028412,0.390000,1.950000,...,0.005540,0.2,0.011081,0.033242,0.000000,0.0,0.0,0.0,0.016621,0.0
32,Demersal sharks and rays,Regular,None,NaN,0.200000,0.364069,0.015831,0.040000,1.260000,6.300000,...,0.032051,0.2,0.050400,0.151200,0.000000,0.0,0.0,0.0,0.082451,0.0
31,Pelagic fish (30+cm),Regular,None,NaN,0.143381,0.282512,0.038000,0.158000,0.900000,6.276998,...,0.102027,0.2,0.198353,0.651213,0.000000,0.0,0.0,0.0,0.300380,0.0
30,Juvenile large pelagic fish,Regular,None,NaN,0.199685,0.607021,0.009600,0.117866,2.870000,14.372630,...,0.132935,0.2,0.338809,1.016960,0.000000,0.0,0.0,0.0,0.471744,0.0
29,Pelagic fish (less than 30cm),Regular,None,NaN,0.234938,0.950000,0.145610,1.035252,2.870000,12.216000,...,0.148559,0.2,2.529327,7.146135,0.000000,0.0,0.0,0.0,2.677886,0.0
28,Melon seed,Regular,None,NaN,0.090688,0.515730,0.010000,0.114000,2.240000,24.700000,...,0.123663,0.2,0.563160,1.997280,0.000000,0.0,0.0,0.0,0.686823,0.0
27,Benthopelagic fish,Regular,None,NaN,0.200000,0.950000,0.030300,0.515545,3.000000,15.000000,...,0.077332,0.2,1.546635,4.639906,0.000000,0.0,0.0,0.0,1.623967,0.0
26,Adult demersal fish (30+cm),Regular,None,NaN,0.231996,0.424258,0.115000,0.195000,1.440000,6.207002,...,0.161668,0.2,0.242073,0.687492,-0.019500,0.0,0.0,0.0,0.403741,0.0
25,Juv demersal fish (30+cm),Regular,None,NaN,0.168168,0.637605,0.028800,0.111599,2.600000,15.460701,...,0.105151,0.2,0.345078,1.090157,-0.011160,0.0,0.0,0.0,0.450229,0.0
24,Demesral fish (less than 30 cm),Regular,None,NaN,0.207262,0.950000,0.090204,1.540864,2.700000,13.027000,...,0.208017,0.2,4.014567,11.897936,0.000000,0.0,0.0,0.0,4.222584,0.0
23,Croakers (30+cm),Regular,None,NaN,0.229461,0.611224,0.044000,0.095000,1.430000,6.232001,...,0.052815,0.2,0.118408,0.337782,-0.009500,0.0,0.0,0.0,0.171223,0.0
22,Juv large croakers,Regular,None,NaN,0.150790,0.955489,0.011000,0.042493,2.360000,15.650918,...,0.004464,0.2,0.133012,0.431763,-0.004249,0.0,0.0,0.0,0.137475,0.0
21,Croakers (less than 30cm),Regular,None,NaN,0.209294,0.783877,0.016000,0.289000,2.360000,11.276000,...,0.147404,0.2,0.651753,1.924971,0.000000,0.0,0.0,0.0,0.799157,0.0
20,Adult groupers,Regular,None,NaN,0.139344,0.375143,0.002900,0.040000,0.850000,6.100000,...,0.021245,0.2,0.048800,0.161200,0.000000,0.0,0.0,0.0,0.070045,0.0
19,Snappers,Regular,None,NaN,0.149154,0.950000,0.005300,0.014007,1.340000,8.984000,...,0.000938,0.2,0.025168,0.081902,0.000000,0.0,0.0,0.0,0.026106,0.0
18,Pomfret (Stromateids),Regular,None,NaN,0.203762,0.950000,0.005300,0.064943,1.300000,6.380000,...,0.004221,0.2,0.082868,0.247044,0.000000,0.0,0.0,0.0,0.087089,0.0
17,Adult hairtail (Trichiurids),Regular,None,NaN,0.241663,0.326777,0.015200,0.042600,1.500000,6.207000,...,0.043019,0.2,0.052884,0.147635,0.000000,0.0,0.0,0.0,0.095903,0.0
16,Juv Hairtail (Trichiurids),Regular,None,NaN,0.171516,0.328816,0.003800,0.034022,2.300000,13.409795,...,0.052520,0.2,0.091245,0.286730,0.000000,0.0,0.0,0.0,0.143765,0.0
15,Lizard fish (Synodontids),Regular,None,NaN,0.425375,0.240568,0.084000,0.300000,2.300000,5.407000,...,0.524008,0.2,0.324420,0.607680,0.000000,0.0,0.0,0.0,0.848428,0.0
14,Bigeyes (Priacanthids),Regular,None,NaN,0.107080,0.328269,0.035000,0.318000,1.210000,11.300000,...,0.258468,0.2,0.718680,2.489940,0.000000,0.0,0.0,0.0,0.977148,0.0
13,Threadfin bream (Nemipterids),Regular,None,NaN,0.091358,0.468959,0.044000,1.040000,0.740000,8.100000,...,0.408689,0.2,1.684800,5.969600,0.000000,0.0,0.0,0.0,2.093489,0.0
12,Cephalopods,Regular,None,NaN,0.387500,0.500000,0.024400,0.468801,3.100000,8.000000,...,0.726642,0.2,0.750082,1.547044,0.000000,0.0,0.0,0.0,1.476724,0.0
11,Crabs,Regular,None,NaN,0.250000,0.950000,0.010000,0.751149,3.000000,12.000000,...,0.112672,0.2,1.802757,4.957582,0.000000,0.0,0.0,0.0,1.915429,0.0
10,Shrimps,Regular,None,NaN,0.186593,0.950000,0.035000,0.425453,5.400000,28.940000,...,0.114872,0.2,2.462525,7.552650,0.000000,0.0,0.0,0.0,2.577397,0.0
9,Sessile/other invertebrates,Regular,None,NaN,0.111111,0.845668,0.001100,3.114000,1.000000,9.000000,...,0.480591,0.2,5.605200,19.306800,0.000000,0.0,0.0,0.0,6.085791,0.0
8,Non-ceph molluscs,Regular,None,NaN,0.428571,0.384763,0.005600,13.747000,3.000000,7.000000,...,25.372991,0.2,19.245800,35.742200,0.000000,0.0,0.0,0.0,44.618791,0.0
7,Benthic crustaceans,Regular,None,NaN,0.210037,0.626794,0.001900,2.649000,5.650000,26.900000,...,5.585726,0.2,14.251620,42.039627,0.000000,0.0,0.0,0.0,19.837346,0.0
6,Echinoderms,Regular,None,NaN,0.335196,0.398951,0.003900,3.065000,1.200000,3.580000,...,2.210658,0.2,2.194540,5.100160,0.000000,0.0,0.0,0.0,4.405198,0.0
5,Polychaetes,Regular,None,NaN,0.300000,0.950000,0.000000,3.435637,6.750000,22.500000,...,1.159527,0.2,15.460365,38.650910,0.000000,0.0,0.0,0.0,16.619893,0.0
4,Jellyfish,Regular,None,NaN,0.250000,0.950000,0.001200,0.146017,5.000000,20.000000,...,0.036504,0.2,0.584068,1.606187,0.000000,0.0,0.0,0.0,0.620572,0.0
3,Zooplanktons,Regular,None,NaN,0.166667,0.052651,0.010000,33.800000,32.000000,192.000000,...,1024.652502,0.3,1946.880000,3461.119630,0.000000,0.0,0.0,0.0,2971.532502,0.0
2,Benthic producers,PP,None,NaN,1.000000,0.020140,0.005574,153.000000,11.890000,11.890000,...,1782.531137,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,1782.531137,0.0
1,Phytoplanktons,PP,None,NaN,1.000000,0.035373,0.000000,323.000000,399.000000,399.000000,...,124318.182689,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,124318.182689,0.0

In [23]:
balanced, p, q = self.is_model_balanced()
print(f'balanced: {balanced}')
groups_df = self.get_groups_df()
groups_df['p-p`'] = p - groups_df['p']
groups_df['q-q`'] = q - groups_df['q']
groups_df.round(5)

balanced: False

,group_name,trophic_info,taxon_descr,tl,ge,ee,catch,biomass,pb,qb,...,egestion,respiration,biomass_accum,emigration,immigration,net_migration,flow_to_det,detritus_import,p-p`,q-q`
group_seq,,,,,,,,,,,,,,,,,,,,,
39,diet_import,Import,NaN,1.0,0.00000,0.00000,0.00000,1.00000,0.00000,0.00000,...,0.00000,0.00000,0.00000,0.0,0.0,0.0,0.00000,0.0,0.00000,0.00000
38,Detritus,DET,None,NaN,1.00000,1.00000,0.00000,100.00000,1291.86868,1291.86868,...,0.00000,0.00000,127035.38968,0.0,0.0,0.0,0.00000,0.0,0.00000,0.00000
37,Seaturtles,Regular,None,NaN,0.02857,0.50304,0.00001,0.00020,0.10000,3.50000,...,0.00014,0.00054,0.00000,0.0,0.0,0.0,0.00015,0.0,0.00000,0.00000
36,Other mammals,Regular,None,NaN,0.01064,0.06812,0.00012,0.01580,0.11200,10.52300,...,0.03325,0.13124,0.00000,0.0,0.0,0.0,0.03490,0.0,0.00000,-0.00000
35,Pinnipeds,Regular,None,NaN,0.00305,0.67927,0.00014,0.00460,0.04500,14.76800,...,0.01359,0.05414,0.00000,0.0,0.0,0.0,0.01365,0.0,0.00000,-0.00000
34,Seabirds,Regular,None,NaN,0.00089,0.00462,0.00000,0.00220,0.06000,67.75900,...,0.02979,0.11902,0.00000,0.0,0.0,0.0,0.02992,0.0,-0.00000,0.00000
33,Pelagic sharks and rays,Regular,None,NaN,0.20000,0.50000,0.00504,0.02841,0.39000,1.95000,...,0.01108,0.03324,0.00000,0.0,0.0,0.0,0.01662,0.0,-0.00000,-0.00000
32,Demersal sharks and rays,Regular,None,NaN,0.20000,0.36407,0.01583,0.04000,1.26000,6.30000,...,0.05040,0.15120,0.00000,0.0,0.0,0.0,0.08245,0.0,-0.00000,-0.00000
31,Pelagic fish (30+cm),Regular,None,NaN,0.14338,0.28251,0.03800,0.15800,0.90000,6.27700,...,0.19835,0.65121,0.00000,0.0,0.0,0.0,0.30038,0.0,-0.00000,0.00000
30,Juvenile large pelagic fish,Regular,None,NaN,0.19969,0.60702,0.00960,0.11787,2.87000,14.37263,...,0.33881,1.01696,0.00000,0.0,0.0,0.0,0.47174,0.0,-0.00000,0.00000
29,Pelagic fish (less than 30cm),Regular,None,NaN,0.23494,0.95000,0.14561,1.03525,2.87000,12.21600,...,2.52933,7.14614,0.00000,0.0,0.0,0.0,2.67789,0.0,-0.00000,-0.00000
28,Melon seed,Regular,None,NaN,0.09069,0.51573,0.01000,0.11400,2.24000,24.70000,...,0.56316,1.99728,0.00000,0.0,0.0,0.0,0.68682,0.0,-0.00000,0.00000
27,Benthopelagic fish,Regular,None,NaN,0.20000,0.95000,0.03030,0.51555,3.00000,15.00000,...,1.54664,4.63991,0.00000,0.0,0.0,0.0,1.62397,0.0,0.00000,0.00000
26,Adult demersal fish (30+cm),Regular,None,NaN,0.23200,0.42426,0.11500,0.19500,1.44000,6.20700,...,0.24207,0.68749,-0.01950,0.0,0.0,0.0,0.40374,0.0,-0.01950,-0.01950
25,Juv demersal fish (30+cm),Regular,None,NaN,0.16817,0.63761,0.02880,0.11160,2.60000,15.46070,...,0.34508,1.09016,-0.01116,0.0,0.0,0.0,0.45023,0.0,-0.01116,-0.01116
24,Demesral fish (less than 30 cm),Regular,None,NaN,0.20726,0.95000,0.09020,1.54086,2.70000,13.02700,...,4.01457,11.89794,0.00000,0.0,0.0,0.0,4.22258,0.0,0.00000,0.00000
23,Croakers (30+cm),Regular,None,NaN,0.22946,0.61122,0.04400,0.09500,1.43000,6.23200,...,0.11841,0.33778,-0.00950,0.0,0.0,0.0,0.17122,0.0,-0.00950,-0.00950
22,Juv large croakers,Regular,None,NaN,0.15079,0.95549,0.01100,0.04249,2.36000,15.65092,...,0.13301,0.43176,-0.00425,0.0,0.0,0.0,0.13748,0.0,-0.00425,-0.00425
21,Croakers (less than 30cm),Regular,None,NaN,0.20929,0.78388,0.01600,0.28900,2.36000,11.27600,...,0.65175,1.92497,0.00000,0.0,0.0,0.0,0.79916,0.0,-0.00000,-0.00000
20,Adult groupers,Regular,None,NaN,0.13934,0.37514,0.00290,0.04000,0.85000,6.10000,...,0.04880,0.16120,0.00000,0.0,0.0,0.0,0.07005,0.0,0.00000,-0.00000
19,Snappers,Regular,None,NaN,0.14915,0.95000,0.00530,0.01401,1.34000,8.98400,...,0.02517,0.08190,0.00000,0.0,0.0,0.0,0.02611,0.0,0.00000,0.00000
18,Pomfret (Stromateids),Regular,None,NaN,0.20376,0.95000,0.00530,0.06494,1.30000,6.38000,...,0.08287,0.24704,0.00000,0.0,0.0,0.0,0.08709,0.0,-0.00000,0.00000
17,Adult hairtail (Trichiurids),Regular,None,NaN,0.24166,0.32678,0.01520,0.04260,1.50000,6.20700,...,0.05288,0.14763,0.00000,0.0,0.0,0.0,0.09590,0.0,0.00000,0.00000
16,Juv Hairtail (Trichiurids),Regular,None,NaN,0.17152,0.32882,0.00380,0.03402,2.30000,13.40979,...,0.09124,0.28673,0.00000,0.0,0.0,0.0,0.14377,0.0,-0.00000,-0.00000
15,Lizard fish (Synodontids),Regular,None,NaN,0.42537,0.24057,0.08400,0.30000,2.30000,5.40700,...,0.32442,0.60768,0.00000,0.0,0.0,0.0,0.84843,0.0,-0.00000,0.00000
14,Bigeyes (Priacanthids),Regular,None,NaN,0.10708,0.32827,0.03500,0.31800,1.21000,11.30000,...,0.71868,2.48994,0.00000,0.0,0.0,0.0,0.97715,0.0,-0.00000,-0.00000
13,Threadfin bream (Nemipterids),Regular,None,NaN,0.09136,0.46896,0.04400,1.04000,0.74000,8.10000,...,1.68480,5.96960,0.00000,0.0,0.0,0.0,2.09349,0.0,-0.00000,-0.00000
12,Cephalopods,Regular,None,NaN,0.38750,0.50000,0.02440,0.46880,3.10000,8.00000,...,0.75008,1.54704,0.00000,0.0,0.0,0.0,1.47672,0.0,-0.00000,0.00000
11,Crabs,Regular,None,NaN,0.25000,0.95000,0.01000,0.75115,3.00000,12.00000,...,1.80276,4.95758,0.00000,0.0,0.0,0.0,1.91543,0.0,-0.00000,0.00000
10,Shrimps,Regular,None,NaN,0.18659,0.95000,0.03500,0.42545,5.40000,28.94000,...,2.46252,7.55265,0.00000,0.0,0.0,0.0,2.57740,0.0,-0.00000,0.00000
9,Sessile/other invertebrates,Regular,None,NaN,0.11111,0.84567,0.00110,3.11400,1.00000,9.00000,...,5.60520,19.30680,0.00000,0.0,0.0,0.0,6.08579,0.0,-0.00000,-0.00000
8,Non-ceph molluscs,Regular,None,NaN,0.42857,0.38476,0.00560,13.74700,3.00000,7.00000,...,19.24580,35.74220,0.00000,0.0,0.0,0.0,44.61879,0.0,-0.00000,-0.00000
7,Benthic crustaceans,Regular,None,NaN,0.21004,0.62679,0.00190,2.64900,5.65000,26.90000,...,14.25162,42.03963,0.00000,0.0,0.0,0.0,19.83735,0.0,-0.00000,-0.00000
6,Echinoderms,Regular,None,NaN,0.33520,0.39895,0.00390,3.06500,1.20000,3.58000,...,2.19454,5.10016,0.00000,0.0,0.0,0.0,4.40520,0.0,0.00000,-0.00000
5,Polychaetes,Regular,None,NaN,0.30000,0.95000,0.00000,3.43564,6.75000,22.50000,...,15.46037,38.65091,0.00000,0.0,0.0,0.0,16.61989,0.0,0.00000,-0.00000
4,Jellyfish,Regular,None,NaN,0.25000,0.95000,0.00120,0.14602,5.00000,20.00000,...,0.58407,1.60619,0.00000,0.0,0.0,0.0,0.62057,0.0,-0.00000,0.00000
3,Zooplanktons,Regular,None,NaN,0.16667,0.05265,0.01000,33.80000,32.00000,192.00000,...,1946.88000,3461.11963,0.00000,0.0,0.0,0.0,2971.53250,0.0,-0.00001,-0.00038
2,Benthic producers,PP,None,NaN,1.00000,0.02014,0.00557,153.00000,11.89000,11.89000,...,0.00000,0.00000,0.00000,0.0,0.0,0.0,1782.53114,0.0,0.00001,0.00001
1,Phytoplanktons,PP,None,NaN,1.00000,0.03537,0.00000,323.00000,399.00000,399.00000,...,0.00000,0.00000,0.00000,0.0,0.0,0.0,124318.18269,0.0,0.00087,0.00087

### model-specific tests

In [3]:
model_path = f'../real_models/new_EwE_jsons/{models_over_10000[5]}'

model = ModelData(model_path)
self = PPRCalculator.from_modeldata(model, underdetermined=True, zero_biomass_accum=False)

self.get_groups_df()

,group_name,trophic_info,taxon_descr,tl,ge,ee,catch,biomass,pb,qb,...,gs,egestion,respiration,biomass_accum,emigration,immigration,net_migration,flow_to_det,detritus_import,det_export
group_seq,,,,,,,,,,,,,,,,,,,,,
25,diet_import,Import,NaN,1.0,0.000000,0.000,0.0,1.00000,0.000000,0.000000,...,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0
24,Detritus,DET,-,NaN,1.000000,1.000,0.0,100.00000,24.119104,24.119104,...,0.0,0.0,0.000000,2025.626983,0.0,0.0,0.0,0.000000,0.0,0.0
23,Marine mammals,Regular,Sousa chinensis,NaN,0.001667,0.000,0.0,0.00404,0.050000,30.000000,...,0.0,0.0,0.120998,0.000000,0.0,0.0,0.0,0.000202,0.0,0.0
22,Sharks,Regular,Scoliodon laticaudus,NaN,0.156250,0.000,0.0,0.00889,0.500000,3.200000,...,0.0,0.0,0.024003,0.000000,0.0,0.0,0.0,0.004445,0.0,0.0
21,Small yellow croakers,Regular,Larimichthys polyactis,NaN,0.477937,0.226,0.0,0.35600,4.300000,8.997000,...,0.0,0.0,1.672132,0.124464,0.0,0.0,0.0,1.184839,0.0,0.0
20,Large yellow croakers,Regular,Larimichthys crocea,NaN,0.433544,0.997,0.0,0.00107,2.130000,4.913000,...,0.0,0.0,0.002978,0.002158,0.0,0.0,0.0,0.000007,0.0,0.0
19,Omnivores,Regular,"Ilisha elongate, Nibea albiflora, Ostorhinchus...",NaN,0.410285,0.999,0.0,0.13600,3.279000,7.992000,...,0.0,0.0,0.640968,0.408925,0.0,0.0,0.0,0.000446,0.0,0.0
18,Benthivores/Piscivores,Regular,"Pennahia argentatus, Nemipterus virgatus, Piso...",NaN,0.419213,0.985,0.0,0.53400,3.910000,9.327000,...,0.0,0.0,2.892678,2.022235,0.0,0.0,0.0,0.031319,0.0,0.0
17,Planktivores/Piscivores,Regular,"Setipinna tenuifilis, Psenopsis anomala, Scomb...",NaN,0.075512,0.353,0.0,2.58800,0.885000,11.720000,...,0.0,0.0,28.040980,0.253034,0.0,0.0,0.0,1.481876,0.0,0.0
16,Planktivores/Benthivores,Regular,"Decapterus maruadsi, Trachurus japonicus, Psen...",NaN,0.110112,0.916,0.0,0.60900,1.176000,10.680000,...,0.0,0.0,5.787936,0.259968,0.0,0.0,0.0,0.060159,0.0,0.0
15,Bombay duck,Regular,Harpadon nehereus,NaN,0.236502,0.956,0.0,0.11000,2.120000,8.964000,...,0.0,0.0,0.752840,-0.002103,0.0,0.0,0.0,0.010261,0.0,0.0
14,Hairtails,Regular,Trichiurus lepturus,NaN,0.170713,0.998,0.0,1.33600,1.104000,6.467000,...,0.0,0.0,7.164968,0.929219,0.0,0.0,0.0,0.002950,0.0,0.0
13,Piscivores,Regular,"Scomberomorus niphonius, Harpadon nehereus, An...",NaN,0.310134,0.804,0.0,0.34800,2.130000,6.868000,...,0.0,0.0,1.648824,0.499622,0.0,0.0,0.0,0.145283,0.0,0.0
12,Benthivores,Regular,"Johnius belangerii, Johnius distinctus, Urocon...",NaN,0.294872,0.995,0.0,0.03970,2.116000,7.176000,...,0.0,0.0,0.200882,0.006100,0.0,0.0,0.0,0.000420,0.0,0.0
11,Planktivores,Regular,"Benthosema pterotum, Bregmaceros macclellandii...",NaN,0.243419,0.998,0.0,0.71000,3.588000,14.740000,...,0.0,0.0,7.917920,0.026929,0.0,0.0,0.0,0.005095,0.0,0.0
10,Cephalopods,Regular,"Abralia multihamata, Euprymna berryi, Loligo b...",NaN,0.300000,0.984,0.0,0.54900,3.000000,10.000000,...,0.0,0.0,3.843000,0.554221,0.0,0.0,0.0,0.026352,0.0,0.0
9,Shrimps,Regular,"Solenocera crassicornis, Trachypenaeus curviro...",NaN,0.265625,0.999,0.0,0.16100,5.100000,19.200000,...,0.0,0.0,2.270100,0.498066,0.0,0.0,0.0,0.000821,0.0,0.0
8,Crabs,Regular,"Portunus trituberculatus, Charybdis feriatus, ...",NaN,0.375000,0.916,0.0,0.14300,4.500000,12.000000,...,0.0,0.0,1.072500,0.161434,0.0,0.0,0.0,0.054054,0.0,0.0
7,Other invertebrates,Regular,Cnidaria,NaN,0.111111,0.616,0.0,3.16000,1.000000,9.000000,...,0.0,0.0,25.280000,0.001775,0.0,0.0,0.0,1.213440,0.0,0.0
6,Echinoderms,Regular,Ophiuroidea,NaN,0.324324,0.182,0.0,3.46000,1.200000,3.700000,...,0.0,0.0,8.650000,-0.000545,0.0,0.0,0.0,3.396336,0.0,0.0
5,Benthic Crustaceans,Regular,"Gammaridea, Cumacea",NaN,0.243866,0.748,0.0,1.60000,6.560000,26.900000,...,0.0,0.0,32.544000,-0.018494,0.0,0.0,0.0,2.644992,0.0,0.0
4,Mollusks,Regular,Bivalves,NaN,0.428571,0.300,0.0,9.51000,3.000000,7.000000,...,0.0,0.0,38.040000,-0.014734,0.0,0.0,0.0,19.971000,0.0,0.0
3,Polychaetes,Regular,Nereis succinea,NaN,0.276860,0.541,0.0,3.13000,6.700000,24.200000,...,0.0,0.0,54.775000,-0.000495,0.0,0.0,0.0,9.625689,0.0,0.0
2,Zooplankton,Regular,"Copepods, Pelagic larva, Chaetognatha, Amphipoda",NaN,0.250000,0.308,0.0,4.70300,40.000000,160.000000,...,0.0,0.0,564.360000,0.033269,0.0,0.0,0.0,130.179040,0.0,0.0
1,Phytoplankton,PP,None,NaN,1.000000,0.205,0.0,16.52000,170.700000,170.700000,...,0.0,0.0,0.000000,0.889261,0.0,0.0,0.0,2241.871380,0.0,0.0

In [4]:
sppr, sppr_det = self._sample_SPPR_new_forced_balance(TE_option='TE')
sppr

c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\PPRCalculator.py:1944: RuntimeWarning: 2 group(s) have TE=0 because EE=0 (M0=p): 23 (Marine mammals), 22 (Sharks). Their consumed PP is re-credited to detritus (fix_EE_0_cases=True) so the TE SPPR stays PP-balanced.
  warnings.warn(

     25            24            1
25  1.0      0.000000      0.000000
24  0.0      0.966130      0.000000
1   0.0      0.000000      1.000000
23  0.0      0.000000      0.000000
22  0.0      0.000000      0.000000
21  0.0    122.916462    199.984041
20  0.0     20.296241     32.602964
19  0.0     30.596284     45.483756
18  0.0     16.485812     20.178818
17  0.0    297.635263    396.919939
16  0.0     36.154583     86.862765
15  0.0     89.963990    197.325057
14  0.0    162.284697    251.581330
13  0.0    102.286766    192.128280
12  0.0    189.297434    217.802518
11  0.0     16.125725     37.478814
10  0.0     11.222714     26.808267
9   0.0      7.623162      7.184768
8   0.0      6.687098      5.117944
7   0.0      5.646214      8.766234
6   0.0  47525.481935  56135.354228
5   0.0      9.475438      5.460981
4   0.0     12.274908      6.329922
3   0.0      6.450285      0.000000
2   0.0      3.764143      9.090909

In [9]:
sppr, A, L = self.SPPR_new(TE=None, TE_option='TE', collapse_det=False, fix_EE_0_cases=True)
sppr, A, L = PPRCalculator.rename_results([sppr, A, L], self.seq2name)
print(self.is_model_balanced()[0])
print(self.get_PPR(sppr, only_inner=True, only_pp=False).sum(axis=1))
print(self.get_PPR(sppr, only_inner=True, only_pp=False).rename(columns=self.seq2name))
print(f'balanced: {self.is_sppr_balanced(sppr)}')
sppr.round(5)

True
catch    0.0
dtype: float64
       Phytoplankton  Detritus
catch            0.0       0.0
balanced: (True, np.float64(2819.964), np.float64(2819.964000000008))

c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\PPRCalculator.py:1944: RuntimeWarning: 2 group(s) have TE=0 because EE=0 (M0=p): 23 (Marine mammals), 22 (Sharks). Their consumed PP is re-credited to detritus (fix_EE_0_cases=True) so the TE SPPR stays PP-balanced.
  warnings.warn(

                          diet_import     Detritus  Phytoplankton
diet_import                       1.0      0.00000        0.00000
Detritus                          0.0      0.96613        0.00000
Marine mammals                    0.0      0.00000        0.00000
Sharks                            0.0      0.00000        0.00000
Small yellow croakers             0.0    122.91646      199.98404
Large yellow croakers             0.0     20.29624       32.60296
Omnivores                         0.0     30.59628       45.48376
Benthivores/Piscivores            0.0     16.48581       20.17882
Planktivores/Piscivores           0.0    297.63526      396.91994
Planktivores/Benthivores          0.0     36.15458       86.86277
Bombay duck                       0.0     89.96399      197.32506
Hairtails                         0.0    162.28470      251.58133
Piscivores                        0.0    102.28677      192.12828
Benthivores                       0.0    189.29743      217.80252
Planktivores                      0.0     16.12572       37.47881
Cephalopods                       0.0     11.22271       26.80827
Shrimps                           0.0      7.62316        7.18477
Crabs                             0.0      6.68710        5.11794
Other invertebrates               0.0      5.64621        8.76623
Echinoderms                       0.0  47525.48194    56135.35423
Benthic Crustaceans               0.0      9.47544        5.46098
Mollusks                          0.0     12.27491        6.32992
Polychaetes                       0.0      6.45028        0.00000
Zooplankton                       0.0      3.76414        9.09091
Phytoplankton                     0.0      0.00000        1.00000

In [11]:
sppr, A, L = self.SPPR_2015(only_pp_det=True)
sppr, A, L = PPRCalculator.rename_results([sppr, A, L], self.seq2name)
print(self.is_model_balanced()[0])
print(self.get_PPR(sppr, only_inner=True, only_pp=False).sum(axis=1))
print(self.get_PPR(sppr, only_inner=True, only_pp=False).rename(columns=self.seq2name))
print(f'balanced: {self.is_sppr_balanced(sppr)}')
sppr.round(5)

True
catch    0.0
dtype: float64
       Phytoplankton
catch            0.0
balanced: (False, np.float64(2819.964), np.float64(2733.0956086624856))

                          diet_import  Phytoplankton
group_seq
diet_import                       1.0        0.00000
Detritus                          0.0        0.92950
Marine mammals                    1.0        0.00000
Sharks                            1.0        0.00000
Small yellow croakers             0.0      318.24026
Large yellow croakers             0.0       52.12970
Omnivores                         0.0       74.92002
Benthivores/Piscivores            0.0       36.03959
Planktivores/Piscivores           0.0      683.27069
Planktivores/Benthivores          0.0      121.64659
Bombay duck                       0.0      283.87816
Hairtails                         0.0      407.71318
Piscivores                        0.0      290.53696
Benthivores                       0.0      399.92295
Planktivores                      0.0       52.99315
Cephalopods                       0.0       37.60548
Shrimps                           0.0       14.51891
Crabs                             0.0       11.55151
Other invertebrates               0.0       14.19838
Echinoderms                       0.0   101858.96054
Benthic Crustaceans               0.0       14.57717
Mollusks                          0.0       18.13944
Polychaetes                       0.0        6.20573
Zooplankton                       0.0       12.71234
Phytoplankton                     0.0        1.00000

In [25]:
# sppr, A, L = self.SPPR_EwE(TE_option='TE', silent=False)
# sppr, A, L = PPRCalculator.rename_results([sppr, A, L], self.seq2name)
# print(self.is_model_balanced()[0])
# print(self.get_PPR(sppr, only_inner=True).sum(axis=1))
# print(f'balanced: {self.is_sppr_balanced(sppr)}')
# sppr.round(3)

In [29]:
# sppr = self.SPPR_1995(global_TE=0.1)
# sppr = self.SPPR_1995(global_TE='mean')
# sppr, A, L = self.SPPR_EwE_Ido(TE_option='TE', use_EE=False)
# sppr,  = PPRCalculator.rename_results([sppr], self.seq2name)
# print(self.is_model_balanced()[0])
# print(self.get_PPR(sppr, only_inner=True).sum(axis=1))
# print(f'balanced: {self.is_sppr_balanced(sppr)}')
# sppr.round(3)

### cross-models tests

In [4]:
# Pipeline: build a summary DataFrame over every model in new_EwE_jsons
ewe_dir = Path('../real_models/EwE_jsons')
model_files = sorted(ewe_dir.glob('*.json'))

balanced_models = []
not_balanced = []

for f in tqdm(model_files):
    try:
        model = ModelData(str(f))
        self = PPRCalculator.from_modeldata(model, underdetermined=True, zero_biomass_accum=False)
        balanced = self.is_model_balanced()[0]
        # print(f'{f.name} - balanced: {balanced}')

        if balanced:
            balanced_models.append(f.name)
        else:
            not_balanced.append(f.name)

    except:
        continue

  0%|          | 0/230 [00:00<?, ?it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 5 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 37 (Shortfinned squid), 17 (Winter flounder), 16 (Witch flounder), 3 (Grey seals), 1 (Walrus).
  warnings.warn(
  3%|▎         | 6/230 [00:00<00:17, 13.15it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 2 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 5 (Sei whales), 4 (Brydes whales).
  warnings.warn(
 13%|█▎        | 30/230 [00:02<00:11, 17.24it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 1 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 1 (Engraulidae).
  warnings.warn(
 17%|█▋        | 38/230 [00:02<00:10, 17.85it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 8 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 29 (Invert-eat Bird), 25 (Capelin), 22 (Eulachon), 14 (Seabirds), 13 (Avian Predators), 10 (Adult Salmon), 2 (Resident Orca), 1 (Transient Orca).
  warnings.warn(
 20%|██        | 47/230 [00:03<00:11, 16.25it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 2 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 9 (Dorado), 3 (Picudos).
  warnings.warn(
 25%|██▍       | 57/230 [00:03<00:10, 16.21it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 10 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 44 (Phytoplankton), 33 (Oyster 1+), 32 (Oyster YOY), 29 (Non-piscivorous seabirds), 28 (Piscivorous birds), 17 (White perch adult), 12 (Menhaden adult), 7 (Weakfish Adult), 5 (Bluefish adult), 3 (Striped bass migratory).
  warnings.warn(
 27%|██▋       | 63/230 [00:04<00:15, 10.61it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 6 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 6 (Tuna/billfish), 5 (Penguins), 4 (Seabirds), 3 (Seal), 2 (Baleen whale), 1 (Toothed whale).
  warnings.warn(
 33%|███▎      | 75/230 [00:05<00:11, 13.22it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 1 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 9 (Sth Rock Lobster).
  warnings.warn(
 37%|███▋      | 84/230 [00:05<00:09, 15.30it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 1 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 28 (Phytoplankton).
  warnings.warn(
 38%|███▊      | 88/230 [00:06<00:11, 12.26it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 4 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 30 (Farfantepenaeus californiensis (ADULTS)), 28 (Litopenaeus stylirostris (ADULTS)), 20 (Litopenaeus stylirostris (JUVENILES)), 19 (Farfantepenaeus californiensis (JUVENILES)).
  warnings.warn(
 40%|████      | 92/230 [00:06<00:14,  9.85it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 14 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 25 (Other turtles), 24 (Leatherback turtle), 20 (Small offshore pelagics), 19 (Coastal predators), 17 (Pelagic sharks), 16 (Dolphinfish), 14 (Mackerels), 13 (Other offshore predators), 11 (Bigeye), 10 (Albacore), 7 (Billfishes), 4 (Killer whales), 3 (Deep-diving whales), 1 (Seabirds).
  warnings.warn(
 44%|████▍     | 102/230 [00:07<00:11, 11.04it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 4 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 29 (chinook juv.), 27 (coho juv.), 25 (chum), 24 (pink).
  warnings.warn(
 45%|████▌     | 104/230 [00:07<00:11, 11.45it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 2 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 25 (chum), 24 (pink).
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 2 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 25 (chum), 24 (pink).
  warnings.warn(
 48%|████▊     | 110/230 [00:08<00:10, 11.05it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 7 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 42 (Benthic algae), 40 (Phytoplankton), 39 (Herbivorous zooplankton), 15 (Carnivorous zooplankton), 5 (Sea lions), 4 (Birds), 2 (Toothed cetaceans).
  warnings.warn(
 50%|█████     | 116/230 [00:08<00:11, 10.21it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 3 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 23 (Turf algae_LB), 6 (Hawksbills), 4 (Rays).
  warnings.warn(
 54%|█████▍    | 124/230 [00:09<00:09, 10.87it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 5 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 37 (Short finned squid), 17 (Winter flounder), 15 (Yellowtail flounder), 3 (Grey seals), 1 (Walrusses).
  warnings.warn(
 55%|█████▍    | 126/230 [00:09<00:09, 10.48it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 2 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 34 (Macroalgae), 26 (cephalopods).
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 2 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 40 (LCsharks), 25 (juv Menhaden).
  warnings.warn(
 56%|█████▌    | 128/230 [00:10<00:11,  9.24it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 2 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 62 (oceanproduction), 61 (climateforcer).
  warnings.warn(
 61%|██████    | 140/230 [00:11<00:08, 10.09it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 1 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 3 (Birds).
  warnings.warn(
 62%|██████▏   | 142/230 [00:11<00:09,  9.10it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 1 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 4 (Birds).
  warnings.warn(
 62%|██████▏   | 143/230 [00:11<00:10,  8.56it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 3 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 32 (crustaces comm), 30 (cephalopodes non-comm), 1 (orque).
  warnings.warn(
 63%|██████▎   | 144/230 [00:11<00:10,  8.32it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 3 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 32 (crustaces comm), 30 (cephalopodes non-comm), 1 (orque).
  warnings.warn(
 63%|██████▎   | 145/230 [00:12<00:10,  8.27it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 4 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 36 (Baleen whales), 6 (Predatory echinoderms), 5 (Other benthos), 4 (Worms).
  warnings.warn(
 66%|██████▌   | 151/230 [00:12<00:08,  8.89it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 5 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 50 (Macrophytes), 16 (Eulachon), 9 (Small squid), 6 (Transient salmon), 1 (Sea Otters).
  warnings.warn(
 71%|███████▏  | 164/230 [00:14<00:07,  8.82it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 1 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 8 (Mesopelagics).
  warnings.warn(
 72%|███████▏  | 165/230 [00:14<00:08,  7.74it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 3 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 28 (Pinnipeds), 25 (Sharks- coastal), 8 (Mesopelagics).
  warnings.warn(
 72%|███████▏  | 166/230 [00:14<00:08,  7.87it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 1 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 30 (Sea Birds).
  warnings.warn(
 74%|███████▍  | 170/230 [00:15<00:07,  8.15it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 1 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 2 (Seabirds).
  warnings.warn(
 75%|███████▍  | 172/230 [00:15<00:07,  7.59it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 3 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 4 (small coastal sharks), 3 (large coastal sharks), 1 (Seabirds).
  warnings.warn(
 78%|███████▊  | 179/230 [00:16<00:06,  7.93it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 2 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 11 (Hake juvenile), 10 (Hake adulte).
  warnings.warn(
 80%|████████  | 185/230 [00:17<00:05,  7.76it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 2 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 13 (juvéniles poiss), 10 (juvenile cephal).
  warnings.warn(
 86%|████████▌ | 197/230 [00:18<00:05,  6.55it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 1 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 3 (seabirds).
  warnings.warn(
 88%|████████▊ | 203/230 [00:19<00:04,  5.95it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 8 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 8 (Benthic invertebrate f. birds), 7 (Surface feeding birds), 6 (Pelag diving birds), 5 (Piscivore benthic bird), 4 (Otters), 3 (Whales), 2 (Harbour seals), 1 (Grey seals).
  warnings.warn(
 94%|█████████▍| 216/230 [00:22<00:02,  5.68it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 2 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 68 (Phytoplankton), 66 (Zooplankton).
  warnings.warn(
 94%|█████████▍| 217/230 [00:22<00:02,  5.05it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 4 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 18 (Small pelagic producers), 17 (Large pelagic producers), 16 (Other meso-zooplankton), 15 (Arctic cod Larvae).
  warnings.warn(
 99%|█████████▉| 228/230 [00:24<00:00,  6.43it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 3 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 40 (birds), 39 (turtles), 6 (Octopus).
  warnings.warn(
100%|█████████▉| 229/230 [00:24<00:00,  6.25it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\ModelData.py:606: RuntimeWarning: 1 group(s) route less than 100% of their flow_to_det to detritus; the remainder is treated as export out of the system: 44 (Sessile epibenthos).
  warnings.warn(
100%|██████████| 230/230 [00:24<00:00,  9.31it/s]

In [13]:
# Pipeline: build a summary DataFrame over every model in new_EwE_jsons
ewe_dir = Path('../real_models/new_EwE_jsons')
model_files = sorted(ewe_dir.glob('*.json'))

def safe(fn):
    """Run fn() and return its result, or np.nan if it raises."""
    try:
        return fn()
    except Exception as e:
        return np.nan


rows = []
for f in tqdm(model_files):
    model = ModelData(str(f))
    try:
        self = PPRCalculator.from_modeldata(model, underdetermined=True, zero_biomass_accum=False)
    except:
        continue

    # SPPR_new TE_option='TE' (default collapse) -> also reused for (4)
    sppr_TE = safe(lambda: self.SPPR_new(TE=None, TE_option='TE')[0])
    # SPPR_new TE_option='TE' with collapse_det=True
    sppr_TE_collapse = safe(lambda: self.SPPR_new(TE=None, TE_option='TE', collapse_det=True)[0])
    # SPPR_new TE_option='GE'
    sppr_GE = safe(lambda: self.SPPR_new(TE=None, TE_option='GE')[0])
    sppr_TE_collapse = safe(lambda: self.SPPR_new(TE=None, TE_option='GE', collapse_det=True)[0])

    rows.append({
        'filename': f.name,                                                                        # (1)
        'n_detritus': len(self.get_DET_seq()),                                                     # (2)
        'model_balanced': self.is_model_balanced()[0],                                             # (3)
        'sppr_balanced_TE': safe(lambda: self.is_sppr_balanced(sppr_TE)[0]),                       # (4)
        'sppr_balanced_collapse_det_TE': safe(lambda: self.is_sppr_balanced(sppr_TE_collapse)[0]), # (5)
        'sppr_balanced_GE': safe(lambda: self.is_sppr_balanced(sppr_GE)[0]),                       # (6)
        'sppr_balanced_collapse_det_GE': safe(lambda: self.is_sppr_balanced(sppr_TE_collapse)[0]), # (7)
        'PPR2NPP_TE_only_pp': safe(lambda: self.get_PPR2NPP_ratio(sppr_TE, only_pp=True)),         # (8)
        'PPR2NPP_TE_all': safe(lambda: self.get_PPR2NPP_ratio(sppr_TE, only_pp=False)),            # (9)
        'PPR2NPP_GE_only_pp': safe(lambda: self.get_PPR2NPP_ratio(sppr_GE, only_pp=True)),         # (10)
        'PPR2NPP_GE_all': safe(lambda: self.get_PPR2NPP_ratio(sppr_GE, only_pp=False)),            # (11)
        'PPR2NPP_1995_TE0.1': safe(lambda: self.get_PPR2NPP_ratio(self.SPPR_1995(global_TE=0.1))),    # (12)
        'PPR2NPP_1995_TEmean': safe(lambda: self.get_PPR2NPP_ratio(self.SPPR_1995(global_TE='mean'))),# (13)
    })

results_df = pd.DataFrame(rows)
results_df

  0%|          | 0/11 [00:00<?, ?it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\PPRCalculator.py:1944: RuntimeWarning: 1 group(s) have TE=0 because EE=0 (M0=p): 14 (Sea lions). Their consumed PP is re-credited to detritus (fix_EE_0_cases=True) so the TE SPPR stays PP-balanced.
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\PPRCalculator.py:1944: RuntimeWarning: 1 group(s) have TE=0 because EE=0 (M0=p): 14 (Sea lions). Their consumed PP is re-credited to detritus (fix_EE_0_cases=True) so the TE SPPR stays PP-balanced.
  warnings.warn(
  9%|▉         | 1/11 [00:00<00:01,  7.47it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\PPRCalculator.py:1953: RuntimeWarning: 4 group(s) have TE=0 because EE=0 (M0=p): 33 (Cetaceans), 32 (Pinnipeds), 31 (Seabirds), 7 (Chrysaora plocamia). Their consumed PP is dropped, so the TE SPPR will not balance (multi-DET: re-credit not applied).
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\PPRCalculator.py:1953: RuntimeWarning: 4 group(s) have TE=0 because EE=0 (M0=p): 33 (Cetaceans), 32 (Pinnipeds), 31 (Seabirds), 7 (Chrysaora plocamia). Their consumed PP is dropped, so the TE SPPR will not balance (multi-DET: re-credit not applied).
  warnings.warn(
 18%|█▊        | 2/11 [00:00<00:03,  2.85it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\PPRCalculator.py:1969: RuntimeWarning: 2 group(s) have near-zero TE (0 < EE << 1): 36 (Other mammals), 34 (Seabirds). Their SPPR is near-singular (inherent to the TE method); the detritus SPPR may be inflated and is not corrected by fix_EE_0_cases.
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\PPRCalculator.py:1969: RuntimeWarning: 2 group(s) have near-zero TE (0 < EE << 1): 36 (Other mammals), 34 (Seabirds). Their SPPR is near-singular (inherent to the TE method); the detritus SPPR may be inflated and is not corrected by fix_EE_0_cases.
  warnings.warn(
 27%|██▋       | 3/11 [00:01<00:04,  1.72it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\PPRCalculator.py:1969: RuntimeWarning: 3 group(s) have near-zero TE (0 < EE << 1): 36 (Other mammals), 35 (Pinnipeds), 34 (Seabirds). Their SPPR is near-singular (inherent to the TE method); the detritus SPPR may be inflated and is not corrected by fix_EE_0_cases.
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\PPRCalculator.py:1969: RuntimeWarning: 3 group(s) have near-zero TE (0 < EE << 1): 36 (Other mammals), 35 (Pinnipeds), 34 (Seabirds). Their SPPR is near-singular (inherent to the TE method); the detritus SPPR may be inflated and is not corrected by fix_EE_0_cases.
  warnings.warn(
 36%|███▋      | 4/11 [00:02<00:04,  1.50it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\PPRCalculator.py:1969: RuntimeWarning: 2 group(s) have near-zero TE (0 < EE << 1): 36 (Other mammals), 34 (Seabirds). Their SPPR is near-singular (inherent to the TE method); the detritus SPPR may be inflated and is not corrected by fix_EE_0_cases.
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\PPRCalculator.py:1969: RuntimeWarning: 2 group(s) have near-zero TE (0 < EE << 1): 36 (Other mammals), 34 (Seabirds). Their SPPR is near-singular (inherent to the TE method); the detritus SPPR may be inflated and is not corrected by fix_EE_0_cases.
  warnings.warn(
 45%|████▌     | 5/11 [00:03<00:04,  1.35it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\PPRCalculator.py:1944: RuntimeWarning: 2 group(s) have TE=0 because EE=0 (M0=p): 23 (Marine mammals), 22 (Sharks). Their consumed PP is re-credited to detritus (fix_EE_0_cases=True) so the TE SPPR stays PP-balanced.
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\PPRCalculator.py:1944: RuntimeWarning: 2 group(s) have TE=0 because EE=0 (M0=p): 23 (Marine mammals), 22 (Sharks). Their consumed PP is re-credited to detritus (fix_EE_0_cases=True) so the TE SPPR stays PP-balanced.
  warnings.warn(
 55%|█████▍    | 6/11 [00:03<00:02,  1.78it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\PPRCalculator.py:1944: RuntimeWarning: 2 group(s) have TE=0 because EE=0 (M0=p): 23 (Marine mammals), 22 (Sharks). Their consumed PP is re-credited to detritus (fix_EE_0_cases=True) so the TE SPPR stays PP-balanced.
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\PPRCalculator.py:1944: RuntimeWarning: 2 group(s) have TE=0 because EE=0 (M0=p): 23 (Marine mammals), 22 (Sharks). Their consumed PP is re-credited to detritus (fix_EE_0_cases=True) so the TE SPPR stays PP-balanced.
  warnings.warn(
 64%|██████▎   | 7/11 [00:03<00:01,  2.22it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\PPRCalculator.py:1944: RuntimeWarning: 2 group(s) have TE=0 because EE=0 (M0=p): 4 (Hexagrammos otakii), 2 (Piscivores). Their consumed PP is re-credited to detritus (fix_EE_0_cases=True) so the TE SPPR stays PP-balanced.
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\PPRCalculator.py:1969: RuntimeWarning: 1 group(s) have near-zero TE (0 < EE << 1): 3 (Sebastes schlegelii). Their SPPR is near-singular (inherent to the TE method); the detritus SPPR may be inflated and is not corrected by fix_EE_0_cases.
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\PPRCalculator.py:1944: RuntimeWarning: 2 group(s) have TE=0 because EE=0 (M0=p): 4 (Hexagrammos otakii), 2 (Piscivores). Their consumed PP is re-credited to detritus (fix_EE_0_cases=True) so the TE SPPR stays PP-balanced.
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\PPRCalculator.py:1969: RuntimeWarning: 1 group(s) have near-zero TE (0 < EE << 1): 3 (Sebastes schlegelii). Their SPPR is near-singular (inherent to the TE method); the detritus SPPR may be inflated and is not corrected by fix_EE_0_cases.
  warnings.warn(
 73%|███████▎  | 8/11 [00:03<00:01,  2.66it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\PPRCalculator.py:1944: RuntimeWarning: 2 group(s) have TE=0 because EE=0 (M0=p): 4 (Hexagrammos otakii), 2 (Piscivores). Their consumed PP is re-credited to detritus (fix_EE_0_cases=True) so the TE SPPR stays PP-balanced.
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\PPRCalculator.py:1969: RuntimeWarning: 1 group(s) have near-zero TE (0 < EE << 1): 3 (Sebastes schlegelii). Their SPPR is near-singular (inherent to the TE method); the detritus SPPR may be inflated and is not corrected by fix_EE_0_cases.
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\PPRCalculator.py:1944: RuntimeWarning: 2 group(s) have TE=0 because EE=0 (M0=p): 4 (Hexagrammos otakii), 2 (Piscivores). Their consumed PP is re-credited to detritus (fix_EE_0_cases=True) so the TE SPPR stays PP-balanced.
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\PPRCalculator.py:1969: RuntimeWarning: 1 group(s) have near-zero TE (0 < EE << 1): 3 (Sebastes schlegelii). Their SPPR is near-singular (inherent to the TE method); the detritus SPPR may be inflated and is not corrected by fix_EE_0_cases.
  warnings.warn(
 82%|████████▏ | 9/11 [00:04<00:00,  3.03it/s]c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\PPRCalculator.py:1944: RuntimeWarning: 3 group(s) have TE=0 because EE=0 (M0=p): 3 (Gruiformes), 2 (Anseriformes), 1 (Charadriiformes). Their consumed PP is re-credited to detritus (fix_EE_0_cases=True) so the TE SPPR stays PP-balanced.
  warnings.warn(
c:\Users\idoca\Desktop\אישי\אקדמיה\תואר שני\מחקר\BTN\FishEstimationAI\PPRCalculator.py:1944: RuntimeWarning: 3 group(s) have TE=0 because EE=0 (M0=p): 3 (Gruiformes), 2 (Anseriformes), 1 (Charadriiformes). Their consumed PP is re-credited to detritus (fix_EE_0_cases=True) so the TE SPPR stays PP-balanced.
  warnings.warn(
100%|██████████| 11/11 [00:04<00:00,  2.58it/s]

,filename,n_detritus,model_balanced,sppr_balanced_TE,sppr_balanced_collapse_det_TE,sppr_balanced_GE,sppr_balanced_collapse_det_GE,PPR2NPP_TE_only_pp,PPR2NPP_TE_all,PPR2NPP_GE_only_pp,PPR2NPP_GE_all,PPR2NPP_1995_TE0.1,PPR2NPP_1995_TEmean
0,13_10013_Humboldt_Current_(1980).json,1,True,True,True,True,True,0.037599,0.052465,0.007102,0.007567,0.053072,0.022330
1,13_11013_Humboldt_Current_(1995-2004).json,4,True,False,True,True,True,0.042612,0.042612,0.008036,-0.015321,0.018804,0.024769
2,36_10036_Northern_South_China_Sea_(1970s).json,1,True,True,True,True,True,0.036368,0.051911,0.000232,0.000522,0.001316,0.000995
3,36_11036_Northern_South_China_Sea_(2000s).json,1,True,True,True,True,True,0.006871,0.010442,0.000769,0.001428,0.004236,0.001090
4,36_12036_Northern_South_China_Sea_Ecobase_(197...,1,False,False,False,False,False,0.035161,0.051230,0.000282,0.000542,0.001560,0.000711
5,47_10047_East_China_Sea_(1997).json,1,True,True,True,True,True,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
6,47_11047_East_China_Sea_(2018).json,1,True,True,True,True,True,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7,48_10048_North_Yellow_Sea_(2019).json,1,True,True,True,True,True,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
8,48_11048_North_Yellow_Sea_(2019).json,1,True,True,True,True,True,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
9,48_12048_Southwestern_Yellow_Sea_(2008).json,1,True,True,True,True,True,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [12]:
results_df['PPR2NPP_TE_all'] / results_df['PPR2NPP_1995_TE0.1']

0        6.727376
1       35.675632
2    14719.707168
3      509.680328
4    17406.426488
5       27.111279
6        0.719737
7      471.597899
8     1336.113457
9        1.030785
dtype: float64