# Preface - fractional TLs (meanTL) to Diet Composition

In 1986's article, the calculation was done in the global level - all fish were assumed to be on TL=2, with TE=0.1.  
In 1995's article the calculation was done with fractional TL for each group of Fish from similar TL. TE was still assumed to be 0.1 globally.  
In the notebook 1995_group2species.ipynb we explore the effect of this aggregation, and see that it doesn't have a significant effect.  

In this notebook we'd check the effect of using fractional TLs, compared to using diet composition to calcualte PPR.
1. we still use global TE=0.1
2. we assume each fish only eats from 2 TLs under it.

Since it seems like the "species group" used in 1995's article are not either commercial or functional groups,  
we will perform the analysis on a sample catch area (the Baltic Sea), and see how converting groups to species can increase PPR.

In [2]:
import pandas as pd

# Database

We are using the same database loaded in 1995_group2species.ipynb;  
It contains catches from the Baltic sea in the years 1988-1991, and TLs taken from 2020's supplementary material.

In [4]:
interesting_cols = [
    'scientific_name',
    'common_name',
    'habitat',
    'tonnes',
    'mean_TL',
]
df = pd.read_excel("Baltic_88-91_group2species.xlsx", usecols=interesting_cols)
df

,scientific_name,common_name,tonnes,habitat,mean_TL
0,Gadus morhua,Atlantic cod,9.858257e+05,benthopelagic,4.09
1,Clupea harengus,Atlantic herring,1.607137e+06,benthopelagic,3.38
2,Perca fluviatilis,European perch,2.821741e+04,demersal,4.35
3,Salmo salar,Atlantic salmon,1.963040e+04,benthopelagic,4.50
4,Sprattus sprattus,European sprat,3.711686e+05,pelagic-neritic,3.01
5,Esox lucius,Northern pike,1.767858e+04,demersal,4.07
6,Platichthys flesus,European flounder,3.103626e+04,demersal,3.32
7,Belone belone,Garfish,4.131295e+03,pelagic-oceanic,4.16
8,Osmerus eperlanus,European smelt,1.977640e+04,pelagic-neritic,3.46
9,Sander lucioperca,Pike-perch,5.035287e+03,pelagic,4.04
10,Scophthalmus maximus,Turbot,1.828528e+03,demersal,4.36
11,Anguilla anguilla,European eel,1.045213e+04,demersal,3.55
12,Merlangius merlangus,Whiting,1.613325e+03,benthopelagic,4.36
13,Salmo trutta,Sea trout,6.258331e+03,pelagic-neritic,3.36
14,Lota lota,Burbot,2.051286e+03,demersal,3.84
15,Limanda limanda,Common dab,6.883943e+03,demersal,3.29
16,Gasterosteus aculeatus,Three-spined stickleback,4.989708e+03,benthopelagic,3.31
17,Cyclopterus lumpus,Lumpfish,1.281479e+03,benthopelagic,3.89
18,Rutilus rutilus,Roach,1.041592e+04,benthopelagic,2.96
19,Pleuronectes platessa,European plaice,3.521742e+03,demersal,3.26
20,Leuciscus idus,Ide,7.916811e+02,benthopelagic,3.79
21,Coregonus albula,Vendace,3.260215e+03,benthopelagic,3.06
22,Mytilus edulis,Blue mussel,1.957579e+04,sessile,2.00
23,Scophthalmus rhombus,Brill,4.346978e+01,demersal,4.42
24,Trachinus draco,Greater weever,3.845270e+01,demersal,4.18
25,Zoarces viviparus,Eelpout,1.478234e+02,demersal,3.47
26,Scomber scombrus,Atlantic mackerel,9.105009e+01,pelagic-neritic,3.63
27,Pollachius pollachius,Pollack,1.810942e+01,benthopelagic,4.32
28,Palaemon serratus,Common prawn,3.494635e+02,benthic,2.69
29,Cyprinus carpio,Common carp,1.286068e+02,benthopelagic,3.06
30,Melanogrammus aeglefinus,Haddock,1.243957e+01,demersal,4.03
31,Squalus acanthias,Picked dogfish,5.055530e+00,benthopelagic,4.37
32,Microstomus kitt,Lemon sole,6.937772e+01,demersal,3.22
33,Solea solea,Common sole,5.947337e+01,demersal,3.21
34,Petromyzon marinus,Sea lamprey,3.000594e+00,demersal,4.37
35,Pollachius virens,Saithe,2.444177e+00,demersal,4.31
36,Merluccius merluccius,European hake,1.171851e+00,demersal,4.42
37,Coregonus oxyrinchus,Houting,1.401711e+01,demersal,3.25
38,Reinhardtius hippoglossoides,Greenland halibut,1.007560e+00,benthopelagic,4.38
39,Anarhichas lupus,Atlantic wolffish,6.199593e+00,demersal,3.55
40,Lamna nasus,Porbeagle,5.852582e-01,pelagic-oceanic,4.57
41,Eutrigla gurnardus,Grey gurnard,2.798701e+00,demersal,3.87
42,Tinca tinca,Tench,3.831892e+00,demersal,3.69
43,Hippoglossoides platessoides,American plaice,9.057393e-01,demersal,4.08
44,Nephrops norvegicus,Norway lobster,3.197415e+00,benthic,2.87
45,Carassius carassius,Crucian carp,1.399905e+00,demersal,3.11
46,Hypophthalmichthys nobilis,Bighead carp,1.679038e+00,benthopelagic,2.38
47,Cancer pagurus,Edible crab,2.501508e-01,benthic,3.10
48,Ostrea edulis,European flat oyster,4.194643e-01,sessile,2.00
49,Aequipecten opercularis,Queen scallop,5.401291e-02,benthic,2.00
50,Thunnus thynnus,Atlantic bluefin tuna,1.142714e-04,pelagic-oceanic,4.45
51,Dicentrarchus labrax,European seabass,1.729810e-04,demersal,3.79
52,Chelidonichthys cuculus,Red gurnard,9.551010e-05,demersal,3.81
53,Echinus esculentus,European edible sea urchin,1.941530e-04,demersal,2.00

# Calculations

In [7]:
import numpy as np

# Define global constants:
TE = 0.1  # global TE, also possible to use 0.119 from 2020's article.

def SPPR(meanTL):
    TL_fraction = meanTL % 1
    TL_int = int(meanTL)
    sppr = (1-TL_fraction) * (1/TE)**(TL_int-1) + TL_fraction * (1/TE)**(TL_int)
    return sppr

In [8]:
df['SPPR'] = df['mean_TL'].apply(SPPR)
df['PPR'] = df['tonnes'] * df['SPPR']

df['classic SPPR'] = df['mean_TL'].apply(lambda x: (1/TE)**(x-1))
df['classic PPR'] = df['tonnes'] * df['classic SPPR']

df

,scientific_name,common_name,tonnes,habitat,mean_TL,SPPR,PPR,classic SPPR,classic PPR
0,Gadus morhua,Atlantic cod,9.858257e+05,benthopelagic,4.09,1810.0,1.784345e+09,1230.268771,1.212831e+09
1,Clupea harengus,Atlantic herring,1.607137e+06,benthopelagic,3.38,442.0,7.103545e+08,239.883292,3.855253e+08
2,Perca fluviatilis,European perch,2.821741e+04,demersal,4.35,4150.0,1.171022e+08,2238.721139,6.317090e+07
3,Salmo salar,Atlantic salmon,1.963040e+04,benthopelagic,4.50,5500.0,1.079672e+08,3162.277660,6.207679e+07
4,Sprattus sprattus,European sprat,3.711686e+05,pelagic-neritic,3.01,109.0,4.045738e+07,102.329299,3.798142e+07
5,Esox lucius,Northern pike,1.767858e+04,demersal,4.07,1630.0,2.881608e+07,1174.897555,2.077052e+07
6,Platichthys flesus,European flounder,3.103626e+04,demersal,3.32,388.0,1.204207e+07,208.929613,6.484393e+06
7,Belone belone,Garfish,4.131295e+03,pelagic-oceanic,4.16,2440.0,1.008036e+07,1445.439771,5.971538e+06
8,Osmerus eperlanus,European smelt,1.977640e+04,pelagic-neritic,3.46,514.0,1.016507e+07,288.403150,5.703575e+06
9,Sander lucioperca,Pike-perch,5.035287e+03,pelagic,4.04,1360.0,6.847990e+06,1096.478196,5.521083e+06
10,Scophthalmus maximus,Turbot,1.828528e+03,demersal,4.36,4240.0,7.752958e+06,2290.867653,4.188915e+06
11,Anguilla anguilla,European eel,1.045213e+04,demersal,3.55,595.0,6.219016e+06,354.813389,3.708555e+06
12,Merlangius merlangus,Whiting,1.613325e+03,benthopelagic,4.36,4240.0,6.840499e+06,2290.867653,3.695915e+06
13,Salmo trutta,Sea trout,6.258331e+03,pelagic-neritic,3.36,424.0,2.653532e+06,229.086765,1.433701e+06
14,Lota lota,Burbot,2.051286e+03,demersal,3.84,856.0,1.755901e+06,691.830971,1.419143e+06
15,Limanda limanda,Common dab,6.883943e+03,demersal,3.29,361.0,2.485104e+06,194.984460,1.342262e+06
16,Gasterosteus aculeatus,Three-spined stickleback,4.989708e+03,benthopelagic,3.31,379.0,1.891099e+06,204.173794,1.018768e+06
17,Cyclopterus lumpus,Lumpfish,1.281479e+03,benthopelagic,3.89,901.0,1.154613e+06,776.247117,9.947445e+05
18,Rutilus rutilus,Roach,1.041592e+04,benthopelagic,2.96,96.4,1.004095e+06,91.201084,9.499435e+05
19,Pleuronectes platessa,European plaice,3.521742e+03,demersal,3.26,334.0,1.176262e+06,181.970086,6.408516e+05
20,Leuciscus idus,Ide,7.916811e+02,benthopelagic,3.79,811.0,6.420534e+05,616.595002,4.881466e+05
21,Coregonus albula,Vendace,3.260215e+03,benthopelagic,3.06,154.0,5.020732e+05,114.815362,3.743228e+05
22,Mytilus edulis,Blue mussel,1.957579e+04,sessile,2.00,10.0,1.957579e+05,10.000000,1.957579e+05
23,Scophthalmus rhombus,Brill,4.346978e+01,demersal,4.42,4780.0,2.077856e+05,2630.267992,1.143372e+05
24,Trachinus draco,Greater weever,3.845270e+01,demersal,4.18,2620.0,1.007461e+05,1513.561248,5.820051e+04
25,Zoarces viviparus,Eelpout,1.478234e+02,demersal,3.47,523.0,7.731164e+04,295.120923,4.362578e+04
26,Scomber scombrus,Atlantic mackerel,9.105009e+01,pelagic-neritic,3.63,667.0,6.073041e+04,426.579519,3.884010e+04
27,Pollachius pollachius,Pollack,1.810942e+01,benthopelagic,4.32,3880.0,7.026455e+04,2089.296131,3.783594e+04
28,Palaemon serratus,Common prawn,3.494635e+02,benthic,2.69,72.1,2.519632e+04,48.977882,1.711598e+04
29,Cyprinus carpio,Common carp,1.286068e+02,benthopelagic,3.06,154.0,1.980544e+04,114.815362,1.476603e+04
30,Melanogrammus aeglefinus,Haddock,1.243957e+01,demersal,4.03,1270.0,1.579825e+04,1071.519305,1.332924e+04
31,Squalus acanthias,Picked dogfish,5.055530e+00,benthopelagic,4.37,4330.0,2.189044e+04,2344.228815,1.185132e+04
32,Microstomus kitt,Lemon sole,6.937772e+01,demersal,3.22,298.0,2.067456e+04,165.958691,1.151384e+04
33,Solea solea,Common sole,5.947337e+01,demersal,3.21,289.0,1.718780e+04,162.181010,9.645451e+03
34,Petromyzon marinus,Sea lamprey,3.000594e+00,demersal,4.37,4330.0,1.299257e+04,2344.228815,7.034079e+03
35,Pollachius virens,Saithe,2.444177e+00,demersal,4.31,3790.0,9.263430e+03,2041.737945,4.990368e+03
36,Merluccius merluccius,European hake,1.171851e+00,demersal,4.42,4780.0,5.601448e+03,2630.267992,3.082282e+03
37,Coregonus oxyrinchus,Houting,1.401711e+01,demersal,3.25,325.0,4.555562e+03,177.827941,2.492635e+03
38,Reinhardtius hippoglossoides,Greenland halibut,1.007560e+00,benthopelagic,4.38,4420.0,4.453415e+03,2398.832919,2.416968e+03
39,Anarhichas lupus,Atlantic wolffish,6.199593e+00,demersal,3.55,595.0,3.688758e+03,354.813389,2.199699e+03
40,Lamna nasus,Porbeagle,5.852582e-01,pelagic-oceanic,4.57,6130.0,3.587633e+03,3715.352291,2.174440e+03
41,Eutrigla gurnardus,Grey gurnard,2.798701e+00,demersal,3.87,883.0,2.471253e+03,741.310241,2.074705e+03
42,Tinca tinca,Tench,3.831892e+00,demersal,3.69,721.0,2.762794e+03,489.778819,1.876780e+03
43,Hippoglossoides platessoides,American plaice,9.057393e-01,demersal,4.08,1720.0,1.557872e+03,1202.264435,1.088938e+03
44,Nephrops norvegicus,Norway lobster,3.197415e+00,benthic,2.87,88.3,2.823317e+02,74.131024,2.370276e+02
45,Carassius carassius,Crucian carp,1.399905e+00,demersal,3.11,199.0,2.785812e+02,128.824955,1.803428e+02
46,Hypophthalmichthys nobilis,Bighead carp,1.679038e+00,benthopelagic,2.38,44.2,7.421346e+01,23.988329,4.027731e+01
47,Cancer pagurus,Edible crab,2.501508e-01,benthic,3.10,190.0,4.752865e+01,125.892541,3.149212e+01
48,Ostrea edulis,European flat oyster,4.194643e-01,sessile,2.00,10.0,4.194643e+00,10.000000,4.194643e+00
49,Aequipecten opercularis,Queen scallop,5.401291e-02,benthic,2.00,10.0,5.401291e-01,10.000000,5.401291e-01
50,Thunnus thynnus,Atlantic bluefin tuna,1.142714e-04,pelagic-oceanic,4.45,5050.0,5.770706e-01,2818.382931,3.220606e-01
51,Dicentrarchus labrax,European seabass,1.729810e-04,demersal,3.79,811.0,1.402876e-01,616.595002,1.066592e-01
52,Chelidonichthys cuculus,Red gurnard,9.551010e-05,demersal,3.81,829.0,7.917787e-02,645.654229,6.166650e-02
53,Echinus esculentus,European edible sea urchin,1.941530e-04,demersal,2.00,10.0,1.941530e-03,10.000000,1.941530e-03

In [9]:
df.to_excel('Baltic_88-91_TL2structure.xlsx', index=False)